### ISSUE TITLE
Saving as SVG through the GTK window outputs a blank image

### ISSUE THREAD

**Issue by rlafuente** [shoebot/shoebot#1]
(original comments by @stuaxo)

Outputting an SVG through the commandline works fine, though. A workaround for now is to make your bot animated (have a draw function)

This only happens on non animated bots. We have to rethink the implementation of save if we want to avoid rerunning the script (and possibly changing the output).

Render implementation probably needs a way to render the last frame to a target.

**Comment by stuaxo** [comment]
Have to revisit this, now the Gtk3 + cairocffi stuff is merged, a lot of the worst hacks are removed, it should be easier.

**Comment by stuaxo** [comment]
Fixed (at last :) ).
