### ISSUE TITLE
Set current version, package and make release

### ISSUE THREAD

**Issue by rlafuente** [shoebot/shoebot#104]
I can take care of this one now, just need confirmation on something: the changelog mentions version 1.2, while setup.py is still 1.1.1. I suppose we go with version 1.2?

That way I can take care of pushing current stuff to PyPI and creating the GitHub release -- their release system is pretty sweet and works as a decent changelog too. I wanted to get back to Shoebot for a viz experiment but realized the versions are not in sync.

It's really beautiful to see all the new changes there, really awesome that you're still hacking on this @stuaxo :-)

**Comment by stuaxo** [comment]
Yup, that would be ace.   Shoebot is still the easiest to hack on and use, so I do [also just had a year to work on whatever I like, which helped].

I've been working a lot on the "boring stuff" of trying to make installation easier - mainly by working on vext.gi (to enable Gtk3 from a virtualenv)..  

It's still not fully working yet, but seems ok-ish, if you have up to date pip + setuptools.

When it's working  ```python setup.py install``` / ```develop``` should be enough to get things running in a virtualenv.

1.2 makes sense ... I'd experiment with installing and see what works / is broken first... I don't imagine it quite works - also the vext stuff, to work in a virtualenv needs up to date pip + setuptools.

**Comment by rlafuente** [comment]
Done! 

I've done some testing to install and run, things look sane enough to push stuff out and get this done with. Still have to test .deb and .rpm generation for inclusion in PyPI, but that shouldn't be a blocker here.

**Comment by stuaxo** [comment]
Great :)  We probably shouldn't be shy of doing some point releases if we find anything...  most of the backlog (that existed in my head mainly) should be covered now, but some things always seem to pop up.

**Comment by rlafuente** [comment]
100% agree! Releases should happen without friction, and I finally documented the steps to do a release, so it'll be smoother now.

Sometime in the near future I want to review the issue tracker and file away older bugs and feature wishes.

**Comment by stuaxo** [comment]
Install might be a little bit flaky over the next few days - but aim is to get it working ... finding out that not only is setuptools pretty hacky but they are working on it quite a bit (+ vext.gi is a hack on top of setuptools) ... fun :)
