### ISSUE TITLE
Problems under  sudo python setup.py  with distutils

### ISSUE THREAD

**Issue by stuaxo** [shoebot/shoebot#107]
Trigged if you do 

```sudo python setup.py install```

without python-setuptools installed.

- [ ] sbot is not installed

- [ ] clean command breaks

**Comment by rlafuente** [comment]
Should `setup.py` confirm that setuptools is installed, and bork if not?

**Comment by stuaxo** [comment]
I'm definitely pro requiring setuptools.   It should probably be added to ```install_dependencies.sh``` too.

The ubuntu package deb for that is  ```python-setuptools``` ... so it's _probably_ the same for other distros.

**Comment by stuaxo** [comment]
^ In other words - yes :)

**Comment by stuaxo** [comment]
Borking on non-availability of setuptools has been enabled.
