### ISSUE TITLE
readthedocs works now, update it.

### ISSUE THREAD

**Issue by stuaxo** [shoebot/shoebot#111]
Now rtd supports cairo and our embedded shoebot, this needs to be updated.

- [x] merge readthedocs branch

- [x] check docs are correct (e.g. "shoebot as a module).

- [x] update rtd

**Comment by stuaxo** [comment]
WIP ...

**Comment by stuaxo** [comment]
https://github.com/rtfd/readthedocs.org/issues/2168

**Comment by stuaxo** [comment]
RTD doesn't have pango installed, which breaks typography.

Have patched shoebot so that everything else will work if Pango is not available, obviously it will die if typography is used.

**Comment by rlafuente** [comment]
AWESOME

The docs look so good now -- serious thanks for all the efforts you've put into this!

**Comment by stuaxo** [comment]
I had other stuff to do, so this was me procrastinating ;)   I swear, by 2030 we will have everything working awesomely :D

I wouldn't have even been looking at Shoebot if not for recent bug reports - so bug reporters and procrastination FTW !
