### ISSUE TITLE
Colors - gradientpath not yet ported to cairo

### ISSUE THREAD

**Issue by AnnaMag** [shoebot/shoebot#113]
Running the code that works in NB1 (uses geo.angle/geo.coordinates/drawpath/oval_
and getting a message:

('Typography not available ', ImportError('No module named pgi',))
Error in the Shoebot script at line 3110  in **init**
    _ctx.canvas.append(self):
3106:         self.dy = dy
3107:         self.spread = spread
3108:         self.angle = angle
3109: 
3110:         _ctx.canvas.append(self)
      ^ AttributeError: 'CairoCanvas' object has no attribute 'append'

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/shoebot-1.2.1-py2.7.egg/shoebot/grammar/livecode.py", line 116, in run
    self.do_exec(self.known_good, self.ns)
  File "/usr/local/lib/python2.7/site-packages/shoebot-1.2.1-py2.7.egg/shoebot/grammar/livecode.py", line 83, in do_exec
    exec source in ns
  File "<string>", line 85, in <module>
  File "/usr/local/lib/python2.7/site-packages/shoebot-1.2.1-py2.7.egg/share/shoebot/lib/colors/**init**.py", line 3110, in **init**
    _ctx.canvas.append(self)
AttributeError: 'CairoCanvas' object has no attribute 'append'

Where is it going off?

**Comment by stuaxo** [comment]
That looks like a bug in out stacktrace mangling code.

Since the linenumber is so high, I think it's inside the colors module, from nodebox - (which is massive).

To get the proper stack trace add ```-V``` to the commandline (for 'verbose') - you've found a bug in shoebots traceback handling.


The  .append  looks like something from nodebox that shoebot should support... 


If this is public code, then definitely paste the example, support for nodebox was mostly made by running public examples.

**Comment by AnnaMag** [comment]
happens when running
https://www.nodebox.net/code//index.php/Growing_things_|_dandelion

**Comment by stuaxo** [comment]
If you find any other examples with the same bug, put the links here for tracking, and/or submit a pull request to add them into ```tests/bots/append_bug```

**Comment by stuaxo** [comment]
Append should be straightforwardish.

The main thing stopping dandelion from not working is lack of support for colors.gradientpath.

It needs porting from CoreImage (mac stuff) to Cairo (open source stuff).   Cairo does have gradients these days, so it should be possible, we definitely need screenshots of gradientpath on Nodebox1 to work from.

The code that needs porting is from line 3122 in colors.__init__.py at the _draw() method.

Some info on cairo gradients
http://zetcode.com/gfx/cairo/gradients/


For now I've made this raise NotImplementedError, but I guess it could fall back to a normal path (?) This needs to be would need checking against Nodebox1 on the mac to see if it works at al.

**Comment by AnnaMag** [comment]
yes, it throws 
NotImplementedError: gradientpath not implemented yet.

**Comment by AnnaMag** [comment]
to make sure I understand it correctly: CoreImage is NB1 (colors.init.py is part of it), and needs to be ported to Cairo to work in Shoebot. Correct?

**Comment by stuaxo** [comment]
Exactly. 

Any code starting with 'CI' or '_ns' or NS is CoreImage, I had a quick look and gradientpath is the only thing left that needs porting.

**Comment by stuaxo** [comment]
The bug in traceback is now fixed, here is what it looks like running 'dandelion.bot':

```
Error in the Shoebot script at line 116  in run
    self.do_exec(self.known_good  self.ns):
95: colors.gradientfill(
96:     rect(0, 0, WIDTH, HEIGHT, draw=False),
97:     bg.darken(0.25),
98:     bg.lighten(0.25),
99:     spread=0.75
    ^ NotImplementedError: gradientpath not implemented yet.

```

**Comment by stuaxo** [comment]
Hrm, just realised that still isn't quite correct + needs some tweaking..
