### ISSUE TITLE
shoebot in OSX crashes (tested with macports).

### ISSUE THREAD

**Issue by AnnaMag** [shoebot/shoebot#114]
Running any of the examples in /shoebot/examples/path_effects 
using sbot gives:

('Typography not available ', ImportError('No module named pgi',))
Error in the Shoebot script at line 226  in _makeColorableInstance
    inst = clazz(self  _args  *_kwargs):
222:             stroke = Color(stroke, mode='rgb', color_range=1)
223:         kwargs['stroke'] = stroke
224: 
225:         kwargs['strokewidth'] = kwargs.get('strokewidth', self._canvas.strokewidth)
226:         inst = clazz(self, _args, *_kwargs)
     ^ TypeError: 'NoneType' object is not callable

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/shoebot-1.2.1-py2.7.egg/shoebot/grammar/livecode.py", line 116, in run
    self.do_exec(self.known_good, self.ns)
  File "/usr/local/lib/python2.7/site-packages/shoebot-1.2.1-py2.7.egg/shoebot/grammar/livecode.py", line 83, in do_exec
    exec source in ns
  File "<string>", line 12, in <module>
  File "/usr/local/lib/python2.7/site-packages/shoebot-1.2.1-py2.7.egg/shoebot/grammar/nodebox.py", line 712, in textpath
    txt = self.Text(txt, x, y, width, height, enableRendering=False, *_kwargs)
  File "/usr/local/lib/python2.7/site-packages/shoebot-1.2.1-py2.7.egg/shoebot/grammar/bot.py", line 247, in Text
    return self._makeColorableInstance(Text, args, kwargs)
  File "/usr/local/lib/python2.7/site-packages/shoebot-1.2.1-py2.7.egg/shoebot/grammar/bot.py", line 226, in _makeColorableInstance
    inst = clazz(self, *args, *_kwargs)
TypeError: 'NoneType' object is not callable

**Comment by stuaxo** [comment]
Hm, there are a few things that can go wrong -  Can you run the diagnostic script here ?

https://gist.github.com/stuaxo/421cf063d14affd96cfb5cc02f866d02


If everything is good, output will look like this:
```
$  python diag.py 
sys.executable:  /home/stu/.virtualenvs/py2/bin/python
virtualenv: /home/stu/.virtualenvs/py2
Python version: ['2.7.11+ (default, Apr 17 2016, 14:00:29) ', '[GCC 5.3.1 20160413]']
dist: ('Ubuntu', '16.04', 'xenial')
linux_distribution: ('Ubuntu', '16.04', 'xenial')
system: Linux
machine: x86_64
platform: Linux-4.4.0-21-generic-x86_64-with-Ubuntu-16.04-xenial
version: #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016
mac_ver: ('', ('', '', ''), '')

import gi [success] /usr/lib/python2.7/dist-packages/gi/__init__.pyc
import pgi [failed]
import vext [success] /home/stu/.virtualenvs/py2/local/lib/python2.7/site-packages/vext-0.5.20-py2.7.egg/vext/__init__.pyc
import shoebot [success] /home/stu/projects/scratch/shoebot/shoebot/__init__.pyc
shoebot - standard module example
[passed]
shoebot - module, using test
[passed]
```

The most important thing is   import gi [success]     if this fails, but pgi succeeds, then anything text will cause an error like the one you are hitting.

**Comment by AnnaMag** [comment]
Both are a fail...

sys.executable:  /usr/local/opt/python/bin/python2.7
virtualenv: no
Python version: ['2.7.11 (default, Jan 22 2016, 08:28:37) ', '[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]']
dist: ('', '', '')
linux_distribution: ('', '', '')
system: Darwin
machine: x86_64
platform: Darwin-14.5.0-x86_64-i386-64bit
version: Darwin Kernel Version 14.5.0: Tue Sep  1 21:23:09 PDT 2015; root:xnu-2782.50.1~1/RELEASE_X86_64
mac_ver: ('10.10.5', ('', '', ''), 'x86_64')

import gi [failed]
import pgi [failed]
import vext [success] /usr/local/lib/python2.7/site-packages/vext/__init__.pyc
import shoebot [success] /usr/local/lib/python2.7/site-packages/shoebot-1.2.1-py2.7.egg/shoebot/__init__.pyc
shoebot - standard module example
('Typography not available ', ImportError('No module named pgi',))
[passed]
shoebot - module, using test
[failed]:
Traceback (most recent call last):
  File "...generative_art/diag.py", line 86, in <module>
    traceback.print_exc()
NameError: name 'traceback' is not defined

**Comment by AnnaMag** [comment]
what is the 'gi' library? where is it coming from?

**Comment by stuaxo** [comment]
You are on Mac.   I'll try and get my mac vm working later and see whats up.

gi is the "gobject repository"... which is basically the language bindings for Gtk3.

Gtk3 is the widgetset used by GIMP, Inkscape and lots of opensource GUI apps.
      
We moved from Gtk2 to Gtk3 last year which might have broke some things, Shoebot worked on OSX before the move, but this may have broken things.

While Shoebot is primarily developed on Linux, it should also still work on OSX and Windows.

**Comment by AnnaMag** [comment]
great! I can't seem to find a way to make 'gi' visible in Shoebot.

**Comment by stuaxo** [comment]
First step is to just get it visible to python, if (via installing gtk3 on homebrew or something similar) you can get this to work:

```python -c "import gi"```

Then you're most of the way there.

This might work, if you are on homebrew:
```brew install pygobject3```

The macports package seems to be called   ```py-gobject3```  I don't have it in front of me right now so can't see how to install.

**Comment by AnnaMag** [comment]
I'm using brew and pygobject3 fixed the problem (I tried only pygobject). Cheers!

import gi [success] /usr/local/lib/python2.7/site-packages/gi/__init__.pyc
import pgi [failed]

**Comment by AnnaMag** [comment]
Btw, how can I draw on canvas (GUI) instead of printing the output to a file (does .svg output by default)?

**Comment by stuaxo** [comment]
Does ```-w``` work for other examples, ( on the mac I tried it freezes) ?

**Comment by AnnaMag** [comment]
I tried a few examples again- freezes every time
