### ISSUE TITLE
flags -o not working

### ISSUE THREAD

**Issue by AnnaMag** [shoebot/shoebot#115]
sbot -w
gives 
ValueError: Namespace Gtk not available for version 3.0

-o flag is not working either (to change from the svg format)

**Comment by stuaxo** [comment]
As long as you have gtk+3 and the pygobject3 stuff installed,   -o seems to work,    -w doesn't have that error - but for me, now -w is just freezing, and I have no clue why right now.

**Comment by AnnaMag** [comment]
After the last update I'm not getting any output file- with or without the -o flag. 
Please check on any of the demo files...

**Comment by stuaxo** [comment]
Should be able to test later -  

I was getting output (as long as I didn't use -w), though this was after installing some packages in homebrew.

I need to retest, with a fresh homebrew install, document + understand more about what's going on.

**Comment by stuaxo** [comment]
Does -o work with pdf, svg or ps ?

I managed to repro the bug in linux with pngs, but other formats work OK here. 

png is treated a bit differently because of the way cairo works, should be able to fix the png part of this.

**Comment by AnnaMag** [comment]
-o with .pdf

Error in the Shoebot script at line 81  in create_rcontext
    surface = cairo.PDFSurface(self._output_vfile(frame)  *size):
77:         """
78:         Called when CairoCanvas needs a cairo context to draw on
79:         """
80:         if self.format == 'pdf':
81:             surface = cairo.PDFSurface(self._output_vfile(frame), *size)
    ^ AttributeError: 'CairoImageSink' object has no attribute '_output_vfile'

Traceback (most recent call last):
  File "/Users/annamagdalenakedzierska/src/shoebot/shoebot/core/canvas.py", line 169, in flush
    self.sink.render(self.size_or_default(), frame, self._drawqueue)
  File "/Users/annamagdalenakedzierska/src/shoebot/shoebot/core/drawqueue_sink.py", line 21, in render
    r_context = self.create_rcontext(size, frame)
  File "/Users/annamagdalenakedzierska/src/shoebot/shoebot/core/cairo_sink.py", line 81, in create_rcontext
    surface = cairo.PDFSurface(self._output_vfile(frame), *size)
AttributeError: 'CairoImageSink' object has no attribute '_output_vfile'

**Comment by stuaxo** [comment]
Should be fixed for .png now.

**Comment by stuaxo** [comment]
vfile should be fixed to, hadn't pushed code to git :/

**Comment by AnnaMag** [comment]
cool, seems to be working. 
How does one set-up size to-fit for pdf and png? The graphics are saved, but cut out

**Comment by AnnaMag** [comment]
how about the "AttributeError: 'CairoCanvas' object has no attribute 'append' "...:)?

**Comment by stuaxo** [comment]
Don't think there is any suport for size to fit, for svg and pdf - sounds like a good feature request though.

Pretty sure Nodebox just cheats - a load of the examples, tended to have things go off the edges, and so need tweaking (of size(.. , ..) and where to place things).

Have unit tests for file output, looking at CI, once that works can add ones for API stuff (like canvas.append)

**Comment by AnnaMag** [comment]
amazing:)

**Comment by stuaxo** [comment]
For the original bug, is it just "-w" that is not working now ?

**Comment by AnnaMag** [comment]
yes, -o and no-flag options are working

**Comment by stuaxo** [comment]
Made the other bug about -w freezing, so this can be closed.
