### ISSUE TITLE
Fix OSX Instructions on Wiki, and README

### ISSUE THREAD

**Issue by stuaxo** [shoebot/shoebot#122]
Installing on OSX should be as simple as running the install script, once you have a suitable environment setup.

HOWEVER:   Yosemite seems to have a freezing issue.

Somebody with a mac needs to go through the whole install process on macports and homebrew and verify the situation.

If the installer works, then remove the redundant wiki pages...  if the freezing issue should be noted (or ideally fixed).

**Comment by rlafuente** [comment]
#132 shows this is possible, added it to the docs in 8c3626e97b24ce0b52c426a8ccd9278c37000c28 with a note to complain if there's problems -- so I think it's time to close this one until new ones pop up
