### ISSUE TITLE
Examples - initial comments should be docstrings

### ISSUE THREAD

**Issue by stuaxo** [shoebot/shoebot#123]
The start of each example should have a docstring like this -

```
"""
Showing how curves work
"""
```

Instead of the current

```
# about:
#    Showing how curves work
```

This way we can get the info from the bot just be importing it and reading __doc__.   That way we could parse info from the examples, which could be useful for documentation generation or anywhere we might want a gallery of examples.

**Comment by stuaxo** [comment]
Maybe awk could be used to do this in a script.

**Comment by rlafuente** [comment]
Done in 3ddb53e7c85b8e2528c05da4ab2de0cd74cbc7e0 -- phew, that was a fair bit of work
