### ISSUE TITLE
Custom sidebar for wiki

### ISSUE THREAD

**Issue by stuaxo** [shoebot/shoebot#124]
Stuff should be seperated into logical areas

https://help.github.com/articles/creating-a-sidebar/

**Comment by rlafuente** [comment]
I moved most of the wiki stuff into the docs, so as not to scatter docs around and let them bitrot, as had been happening. Maybe we can close this one, or make a new one for moving the remaining wiki content elsewhere

**Comment by stuaxo** [comment]
Makes sense, the less different places to maintain stuff, the less bitrot.

**Comment by stuaxo** [comment]
I had a quick look at the wiki page "how we can help".

At the moment the format is basically, "list of things".

If we want users to help, we need more of a journey.

e.g. we just say "create bots", but have no links to getting started.

The other sections could use similar improvements (though a lot is probably covered by other parts of the docs).

**Comment by rlafuente** [comment]
I had started a [Contributing](http://shoebot.readthedocs.io/en/latest/contributing.html) section on the docs exactly for this purpose, but didn't copy over everything.

You're right in that we should work on the onboarding side of telling people how to get into these tasks.

**Comment by rlafuente** [comment]
Included all of those in the Contributing section in a71507e36946af0f77d6b04759cfb98a8badbc13

I'll be deleting the wiki page now.
