### ISSUE TITLE
Seperate examples into another package + reorg

### ISSUE THREAD

**Issue by stuaxo** [shoebot/shoebot#126]
Examples should be a separate package and repo (as a submodule in the current directory).

Disadvantages:

More users have to run this command -

``` sh
git init submodule
git update submodule
```

Advantages:
- Remove a lot of dependencies from setup.py

(Maybe we can have a script, like servo browser does).

The code inside extensions/lib could be cleaned up into an API for iterating the examples, which would be better for docs etc.

We might want to have

Ideally the setup.py for shoebot will have plugins (like ipython does)

Install shoebot + examples:

```
shoebot[examples]
```

Install shoebot + gtk support:

```
shoebot[gtk]
```

**Comment by stuaxo** [comment]
@rlafuente does this make sense?    Seems like we could sort out the dependency nightmare at the cost of a little complexity.

**Comment by rlafuente** [comment]
Looking at this, I'm really not sure -- since examples are the first contact a new user would have with Shoebot.

More seasoned users looking to use it as a module might not need the examples, but they're pretty vital for newcomers to have at the ready, imho.

**Comment by stuaxo** [comment]
Yeah, maybe I was over-complexifying here.

This would need some thought to make something balanced between being optimal for developers and new users.

I'll close this for now, if any of us gets round to actually testing out some re-orgs then we can re-open.
