### ISSUE TITLE
Vext breaks setup.py

### ISSUE THREAD

**Issue by tian2992** [shoebot/shoebot#130]
Could we have a flag to enable-disable vext that is default as disabled, this could simplify significantly building self-contained packages, such as docker images, debs/rpms, etc. While keeping the chance to install it as a venv'd package.

**Comment by tian2992** [comment]
Of course, this can and probably will require changes to the structure, but it might reduce the complexity of "magical" imports

Thoughts on this @stuaxo ?

**Comment by stuaxo** [comment]
Can you open a bug against vext about how it is breaking ?

We definitely need changes to simplify setup.py (and probably the other code).

I don't have much free time at the moment, but I can help out if you are up for starting ?

Maybe create a new branch with a minimal setup.py that just installs shoebot, then we can think about what to do about examples, extensions and working in a virtualenv.

Possibly in the future some of the functionality, like extensions could become plugins of setup.py, enabling something like:

```python setup.py install shoebot[examples]```

But this is getting ahead of things.

**Comment by stuaxo** [comment]
Closing as vext is not used any more (pygobject can install in a virtualenv now)
