### ISSUE TITLE
Window Mode failing on OSX High Sierra

### ISSUE THREAD

**Issue by dreerr** [shoebot/shoebot#132]
Trying to use Window Mode in OSX always ends in:
```
018-04-28 12:19:48.846 python[50520:1521163] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'nextEventMatchingMask should only be called from the Main Thread!'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff49d4d32b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff713c7c76 objc_exception_throw + 48
	2   AppKit                              0x00007fff479f9297 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 4167
	3   libgdk-3.0.dylib                    0x000000010489e5f4 poll_func + 172
	4   libglib-2.0.0.dylib                 0x00000001042c182f g_main_context_iterate + 340
	5   libglib-2.0.0.dylib                 0x00000001042c16c8 g_main_context_pending + 48
	6   libgtk-3.0.dylib                    0x0000000107ae6e6b gtk_events_pending + 18
	7   libffi.6.dylib                      0x0000000104394914 ffi_call_unix64 + 76
	8   ???                                 0x0000700007c39b70 0x0 + 123145432570736
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```
Any idea how to solve this?

**Comment by rlafuente** [comment]
From a quick search for that error, it appears this has to do with our use of cairocffi and its apparent use of parallel threads. Probably using pycairo instead of cairocffi would help in this case.

But I'm not knowledgeable on that front (and don't have a Mac to test this), maybe @stuaxo can weigh in here.

**Comment by stuaxo** [comment]
I should be able to have a go at reproducing this next week.

**Comment by dreerr** [comment]
Sorry for the inconvenience, I must have mixed up the command line flags. In fact it works with --disable-background-thread` 

Thank you very much for your support @rlafuente and @stuaxo

**Comment by stuaxo** [comment]
Maybe ```--disable-background-thread``` should be the default on OSX ?

We would need a way to enable it again, so maybe it should be along the lines of

```--background-thread=yes / no / default```

Where default is yes on all platforms except OSX ?

**Comment by stuaxo** [comment]
Updated disable background thread to default to true on OSX.

This might mean the interactive shell cannot be used there.
