### ISSUE TITLE
ReadTheDocs builds are failing

### ISSUE THREAD

**Issue by rlafuente** [shoebot/shoebot#134]
and I don't know why

* [most recent passed build](https://readthedocs.org/projects/shoebot/builds/6526194/) was around 3 months ago
* since then builds have been failing and I'm not sure why -- [here's one](https://readthedocs.org/projects/shoebot/builds/7112730/)

any clue @stuaxo ?

**Comment by rlafuente** [comment]
Ok probably [this commit](https://github.com/shoebot/shoebot/commit/231f554f2cce8178aaadf7a5f48d8dd0e33c6b62) of mine is to blame, oops

**Comment by rlafuente** [comment]
Reverted the commit and all is well. Sorry for the noise

**Comment by stuaxo** [comment]
Awesome... nice to know they still work.
