### ISSUE TITLE
Window doesn't close on Ctrl-C

### ISSUE THREAD

**Issue by rlafuente** [shoebot/shoebot#135]
Pressing Ctrl-C on the terminal should kill the running script but doesn't, forcing us to use Ctrl-\ to kill it.
Probably Ctrl-C on the window should kill it as well, since we're at it.

**Comment by stuaxo** [comment]
It's definitely a bug if the terminal doesn't shut with ctrl-c.    I'm not convinced about the window, since it is normally copy in gui apps.

OTOH I'm probably kidding myself if I think we will implement clipboard (though it would make sharing images of bots incredibly easy).

**Comment by rlafuente** [comment]
You're completely right about the expected copy behaviour in the GUI, that shouldn't kill the window.

**Comment by stuaxo** [comment]
It's something to do with using the background thread since it works with ```--disable-background-thread```.

**Comment by stuaxo** [comment]
OK, that should work again now.
