### ISSUE TITLE
Make windowed mode (-w) the default

### ISSUE THREAD

**Issue by rlafuente** [shoebot/shoebot#139]
Right now, the behaviour of `sbot examples/test.bot` is to create `test.svg`, without any feedback other than the file creation.

I was thinking this is not intuitive for new users. Also, anyone using the "headless" mode would most likely specify the output filename with `-o`. Finally, windowed mode is really useful for testing scripts before outputting to a file, so it's something almost everyone in the CLI would use.

Maybe it'd make sense to make windowed mode the default behaviour of `sbot`?

**Comment by stuaxo** [comment]
Makes sense, we should have done this a long time ago.
