### ISSUE TITLE
Add "shoebot" command to launch the IDE?

### ISSUE THREAD

**Issue by rlafuente** [shoebot/shoebot#144]
Right now, the command line runner is `sbot`, and we used to have `shoebot-ide` for the IDE.

Since the IDE would be the first point of entry for new users, and `shoebot` would be the natural command to try running after installing, I'm thinking that maybe `shoebot` could call the IDE.

What do you think @stuaxo ?

**Comment by stuaxo** [comment]
Seems to make sense.
