### ISSUE TITLE
Python 3.

### ISSUE THREAD

**Issue by stuaxo** [shoebot/shoebot#151]
To remain viable, we probably need a story for python 3.

nodebox1 is based on python 2 - so any python3 shoebot is no longer compatible... it will mostly be print statements that cause issues (though lots of external bots have these).

For all the code we control we could probably support 2 and 3.

A first step would be to use the print function everywhere in the code we control.

In the long term I've got all sorts of ideas for rebuilds / or libraries that include shoebot like functionality, but that's happening slowly enough, that I think we should consider moving shoebot to python 3.

Possibly the new version would have a new name (shoebot2?, shoebot3?)

Any thoughts on this ?

**Comment by stuaxo** [comment]
A Python 3 version could simplify some things - we only only have background thread because python 2 doesn't have nonblocking readline.

There are other possibilities, but initially I wouldn't want us to deviate too far.

**Comment by rlafuente** [comment]
100% agreed. I think Py3 compat is a higher priority than keeping support for older stuff -- especially if it helps us regarding threads. And we can add a note in the docs with things to keep in mind when opening old Nodebox scripts.

**Comment by stuaxo** [comment]
OK, we probably want travis setup to run us on python 3.    

I don't imagine breaking python 2 compatibility straight away, so we can probably get at least one python 2 supporting release in first.

**Comment by stuaxo** [comment]
Wow, so many tickets - everything has already been answered.

It would be way better if we could present a python 3 based Shoebot to LGM, what with python 2.7 being soon EOL.

Getting a straight port to python 3.6 working (with no changes) should be a relatively mechanical task.

Not sure, what we should call it - Shoebot2 ?

If I had to choose *one* API change to get done before LGM for Py3 Shoebot, I'd make the origin of Paths etc be the center by default, it makes drawing with symmetry so much easier.

**Comment by stuaxo** [comment]
This should probably be Shoebot 2.

**Comment by rlafuente** [comment]
Now that Python 3 support has been merged to master, we're probably done here -- closing :-)
