### ISSUE TITLE
Support pycairo 1.17.0's equivilent of PycairoContext_FromContext

### ISSUE THREAD

**Issue by dreerr** [shoebot/shoebot#169]
Dear all,

I updated my Python install to 2.7.15 and created a new virtualenv for shoebot to test it. The diagnose comes up with the following:
``` 
import gi                   [success] : [...]
import gi.repository.Pango  [success] : [...]
import pgi                  [failed]
import vext                 [success] : [...]
import pubsub               [success] : [...]
import meta                 [success] : [...]
import shoebot              [success] :[...]
shoebot - standard module example:
Traceback (most recent call last):
[...]
File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 384, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(0x7fc8dd1ba740, PycairoContext_FromContext): symbol not found
[failed]
```

Any idea how to solve this? Never had this error before. My pip freeze looks good to: 
```
cairocffi==0.7.2
cffi==1.11.5
fuzzywuzzy==0.5.0
meta===-
numpy==1.14.3
Pillow==5.1.0
planar==0.4
pubsub==0.1.1
pycparser==2.18
PySoundCard==0.5.2
ruamel.ordereddict==0.4.13
ruamel.yaml==0.15.37
shoebot==1.2.2
vext==0.7.0
vext.gi==0.6.8
```

Thank you for your help!

**Comment by stuaxo** [comment]
I've hit a lot of issues around PycairoContext_FromContext,. I can't look at it now, but will have a look later.

You can try various combinations of installing / uninstalling cairocffi and pycairo.

I would try the latest versions of both first and see if it helps.

**Comment by dreerr** [comment]
Sadly no combination worked out yet. Also changing back to Python 2.7.14 didn‘t help. Any other direction you could point me in?

**Comment by stuaxo** [comment]
I @dreerr does it work with pycairo 1.16.3 and die with newer ones like 1.17 ?

If that's the issue, it may be an issue on pycairo, and I'd like to be able to isolate it.

**Comment by stuaxo** [comment]
Upstream bug - https://github.com/pygobject/pycairo/issues/113

**Comment by stuaxo** [comment]
The solution in this thread needs to be implemented ..

https://github.com/pygobject/pycairo/issues/59#issuecomment-316442034

No reason we can't support both until 1.17.0 is old enough to be everywhere.

**Comment by stuaxo** [comment]
Should be fixed in master.
