### ISSUE TITLE
Review and merge back Jupyter branch

### ISSUE THREAD

**Issue by rlafuente** [shoebot/shoebot#182]
It'd be good to have @stuaxo 's eyes over it before going ahead.

**Comment by stuaxo** [comment]
Cheers - will do in the next few days - but if I haven't looked by Wednesday  - then definitely poke me.

**Comment by stuaxo** [comment]
The style changes definitely improve things, cheers :)  I separated them and commited them, to make it easier to see whats in this branch.

I'd probably need to stare at this a bit to work out going on, this is mostly a function of the snapshot function being a bit over-complex before you started.

I'm going to move conversation on this to a PR - we get CI (which caught a small indentation bug in the style thing) and it's easier to compare stuff.

PR - https://github.com/shoebot/shoebot/pull/187

**Comment by stuaxo** [comment]
Not sure I remember the status of this, is it working?

**Comment by rlafuente** [comment]
I'm really not sure, but from https://github.com/shoebot/shoebot/pull/187 I think it was merged back into master, no?

**Comment by rlafuente** [comment]
just confirmed, it's all on `master` closing!

**Comment by stuaxo** [comment]
Great this is actually a pretty good feature to make the release interesting.
