### ISSUE TITLE
Shoebot logo example

### ISSUE THREAD

**Issue by stuaxo** [shoebot/shoebot#183]
It would be good if our default example in shoebot was the robot logo (or an update of it).

@rlafuente do you have one somewhere ?

**Comment by rlafuente** [comment]
just whipped up this one:

```
size(140, 140)
background(0.9)
fill(0.5)
translate(20, 20)

rect(0, 0, 20, 20)
rect(20, 0, 20, 20)
rect(40, 0, 20, 20)
rect(60, 0, 20, 20)
rect(80, 0, 20, 20)

rect(0, 20, 20, 20)
rect(40, 20, 20, 20)
rect(60, 20, 20, 20)

rect(0, 40, 20, 20)
rect(20, 40, 20, 20)
rect(40, 40, 20, 20)
rect(60, 40, 20, 20)
rect(80, 40, 20, 20)

rect(0, 60, 20, 20)

rect(0, 80, 20, 20)
rect(20, 80, 20, 20)
rect(40, 80, 20, 20)
rect(60, 80, 20, 20)
rect(80, 80, 20, 20)
```

**Comment by rlafuente** [comment]
Surely that can be made better (with a function that takes grid indexes instead of absolute units, and variables for grid size, etc) but done is better than perfect :-)

**Comment by stuaxo** [comment]
I just chucked it in https://github.com/shoebot/shoebot/blob/master/examples/basic/shoebot.bot

Feel free to move it more prominent / rename - originally I was going to stick it in the root of examples and call it bot.bot ... root isn't ideal for the Gedit shoebot examples menu though.

**Comment by rlafuente** [comment]
Perfect!
