### ISSUE TITLE
Next release (1.3 ?)

### ISSUE THREAD

**Issue by stuaxo** [shoebot/shoebot#202]
Quick ticket for the next release, 1.3

Release goals:

This release is mostly about behind the scenes work, and releasing some small fixes.

Features
- Reinstated IDE (alpha status, next release will be beta status)
- Dark theme for IDE
- Lots of documentation improvements
- Lots of small bugfixes
- Improved installation process
  - Update packages in install script so install is successful on lots of distros again

Behind the scenes
- Move back to pycairo by default
  - Should be easier to install, no more vext.gi
  - We now work in pypy by default (due to work upstream, in pypy, pygobject and pycairo).
- Start implementing graphics backend
  - Groundwork for future work backends
  - Easily toggle between cairo/cairocffi and gi/pgi
- Consolidate bug fixes + documentation.
- Lots of refactoring/cleanups of the IDE code to make it easier to modify.

TODO:

- [x] Update setup.py to use pycairo not cairocffi.
- [ ] Document that we now work in pypy by default 

Stretch goals

- Try installing on other platforms and update install script and instructions https://github.com/shoebot/shoebot/issues/108
    - Other linuxes (which ones?)
    ~~Red hat / Fedora testing / info is needed~~
    Install updated script for Fedora
    ~~- MINGW64 https://github.com/shoebot/shoebot/issues/129~~ 
      needinfo - currently too difficult
    ~~- MiniConda https://github.com/shoebot/shoebot/issues/128~~
      needinfo - currently too difficult
     SuSE 
           ~~Output is double size https://github.com/shoebot/shoebot/issues/205~~
           Will defer

- [ ] Set filename in output https://github.com/shoebot/shoebot/issues/155
- [x] Run diagnose outside of setup.py https://github.com/shoebot/shoebot/issues/203

What else ?
- [x] Dark mode patch for IDE? https://github.com/shoebot/shoebot/tree/darktheme

This is a small release to pull together changes in docs, installation improvements and patches over the years.

**Comment by stuaxo** [comment]
OK, MiniConda and MSYS have flummoxed me again, just like they do every time I try and use them.

Until there are straightforward instructions for Pygobject, Gtk3 + Cairo with python2, this isn't going to happen.
When we move to python3 it might get easier as newer libraries seem better supported.

**Comment by stuaxo** [comment]
Open question:  Assuming pygobject + virtualenv play well together, then it's probably worth moving the pygobject dependency to setup.py.

**Comment by stuaxo** [comment]
There are a bunch of cleanups to ide.py that should be extracted from #189 

While that bug eventually turned into the pluginize work, it's worth getting the cleanups out of it before this release.

**Comment by stuaxo** [comment]
OK, I don't think anything is stopping this now.

**Comment by rlafuente** [comment]
Awesome! I'm now writing the changelog for the releases. Here's what I got at the moment.


> Features
> - The Shoebot Editor (IDE) is back as an easy way to edit and run scripts. Its code has been substantially refactored as well. This feature is currently in alpha status, moving to beta on the 1.4 release after some testing.
> - Jupyter notebooks are now supported, through the use of the jupyter-shoebot extension.
> - New dark theme for the IDE.
> - Improved the installation process significantly, with package lists updated to play nice with most distros. Fedora and SUSE were particularly targeted here, improving many annoyances that made running Shoebot in these distros rather difficult.
> - Many documentation improvements
> - Many bug fixes
> 
> Backend
> - Migrate graphics backend into PyCairo by default
> - Easy toggle between Cairo/CairoCFFI and gi/pgi
> - PyPy support is now default

I don't get the meaning of the last point, and would like to be more verbose in outlining the PyPy support. Can you help me understand what's been made here?

Also, anything important that's missing?

**Comment by stuaxo** [comment]
Agreed, I'll have a think about how the backend section can make more sense.

**Comment by stuaxo** [comment]
Here's what changed on the backend in a English, not some half-written bullet-points - 


Work on the graphics backend makes it possible to choose the cairo, and gobject binding using an environment variable.

The default cairo implementation is now pycairo.

Shoebot benefits from upstream fixes to both pycairo and pygobject, and now runs under Pypy without any special configuration.

**Comment by stuaxo** [comment]
-- let me make sure to test SB before mentioning the last sentence.

Also, need to write something about the scaling - I'm not quite sure how to explain it 
- the result is that everything is drawn with vectors at the right size, and doesn't look pixelated as the window scales up.

**Comment by stuaxo** [comment]
Scaling:

Shoebot now renders at the window size not, the bot size meaning vectors stay smooth at any size.


Looks like I need to add pygobject as a requirement - I removed it to get travis working, will add + update here.

**Comment by stuaxo** [comment]
OK, merging gobject fix + works on travis.

Really wanted to make sure our (few) tests were working for this release ready for the next round of stuff.

**Comment by stuaxo** [comment]
@rlafuente I need to do a final round of testing to get pygobject working happily with ordinary python, travis and pypy should get some time to look at this tomorrow.

**Comment by stuaxo** [comment]
OK, works for me (tm) now.

installed and ran hypnoval on cpython and pypy.

**Comment by rlafuente** [comment]
Great to hear!! Here's another try, after editing and reordering:

> * The Shoebot Editor (IDE) is back as an easy way to edit and run scripts. Its code has been substantially refactored as well. This feature is currently in alpha status, moving to beta on the 1.4 release after some testing.
> * New dark theme for the IDE.
> * Jupyter notebooks are now supported, through the use of the jupyter-shoebot extension.
> * PyPy support. Shoebot benefits from upstream fixes to both pycairo and pygobject, and now runs under PyPy without any special configuration.
> * Improved the installation process significantly, with package lists updated to play nice with most distros. Fedora and SUSE were particularly targeted here, improving many annoyances that made running Shoebot in these distros rather difficult.
> * Migrate graphics backend into PyCairo by default.
> * Easy toggle between Cairo/CairoCFFI and gi/pgi as a graphics backend. Recent work on the graphics backend now makes it possible to choose the Cairo and GObject bindings using an environment variable.
> * Many documentation additions and edits
> * Several bug fixes

I'd love to verbosely list all bugs and small fixes, but that way I'll never get this out.

**Comment by stuaxo** [comment]
No we wouldn't get it out.

This looks good, and is nice and readable.

**Comment by stuaxo** [comment]
Oh, dont forget the scaling thing, it really makes a difference.

If you run Shoebot and make the window big or fullscreen you'll see what I mean.

**Comment by rlafuente** [comment]
Arf, completely missed that one. Edited the list above.

**Comment by rlafuente** [comment]
Done: [release on GitHub](https://github.com/shoebot/shoebot/releases/tag/v1.3) and [PyPI project page](https://pypi.org/project/shoebot/).

Will now update the docs with more precise steps to make a release. Phew :-) good to close?

**Comment by stuaxo** [comment]
Hm, need to do a bit of testing on the gedit extension now.

**Comment by stuaxo** [comment]
Great, that all sounds good.

I had a moment just then when I thought the gedit plugin wasn't working, but it was the version from the plugin branch, phew :)

Yep, good to close, will do now.

**Comment by stuaxo** [comment]
Doh, I there is a typo in the setup.py I put in late last night, pybobject.

I force pushed a fix earlier, so we might need a 1.3.1 !

**Comment by stuaxo** [comment]
Ah, just noticed the VERSION file has 1.2 as the version number in it.

OT:  I'm unfamiliar with the format, any idea what it's for ?

**Comment by rlafuente** [comment]
People won't be rushing to get the very latest version, so I guess we can safely wait a week and test further to see if there's more improvements to fit in 1.3.1? I plan to take some time to test with some notebooks + gather example script for the homepage.

(and tbh I really don't remember what VERSION is for. It's been a long time since I fiddled with the install/packaging code, now I just run commands :p )

**Comment by stuaxo** [comment]
OK, waiting sounds good.

I'll open a new ticket for 1.3.1
