### ISSUE TITLE
OpenSuSE renders double size

### ISSUE THREAD

**Issue by stuaxo** [shoebot/shoebot#205]
On OpenSuSE Leap shoebot renders 2x size in the correct size Window.

Maybe HiDPI?

See what cairos device scaling can do.

**Comment by stuaxo** [comment]
![image](https://user-images.githubusercontent.com/179677/54858070-85b0c400-4cfa-11e9-9a85-4238051b43c6.png)

**Comment by stuaxo** [comment]
Have reproduced on Fedora now.

**Comment by stuaxo** [comment]
Had a look at the scaling and the backing store and this could do with a bit of simplification.

There are two ideas -

Scale up the incoming context to be the size of the window (currently the size of the backing store).

And if we are doing a redraw just scale the backing store and draw that.


We should have a function that can return the current backing store or a new one if the scale is different.
To make this not reallocate a backing store, we should snap up to something like the nearest larger 128 pixels.

We will need to store what some info with the backing store about what was last drawn onto it (the size, and frame at least) - if these are the same redraw the backing store.

We might want to scale the backing store if there is no new frame available.

**Comment by rlafuente** [comment]
I can't say much as it's rather low-level stuff, but I'd say go for the simplest way so we can move ahead quickly, and later refine the fix?

Also, should we treat this one as a blocker for 1.3? I ask just to figure out when to begin taking care of the new release.

**Comment by stuaxo** [comment]
I think it should be as rendering is the wrong size.

I've got a minimal version working this evening I'll clean it up then we're good - obviously there is almost infinite work in refining, so I'll hold off beyond getting this working.

**Comment by stuaxo** [comment]
WIP on this branch.

https://github.com/shoebot/shoebot/tree/fix/scale-fix-wip

I'll remove the grey border and make sure there's no debug / hacky things from this branch then we'll be ready for release.

This affects other distros I tried in gnome boxes, like Fedora - so worth waiting.

**Comment by stuaxo** [comment]
@rlafuente this is almost ready (I need to do some basic cleanups and fix the border).

It would be good if you could do some testing on this vs the existing version.

I've moved where scaling happens, so it's worth checking if images saved when the window is bigger are still the correct size (the size specified by the bot).

The cool thing, is that as you scale up the window we are not pixelated any more.
The trade-off is that scaling could be one frame behind the actual size, but the change is minimal one.

**Comment by stuaxo** [comment]
OK, fix is merged - do some testing and if you think we're good to go then let's release it.
