### ISSUE TITLE
Error on "pip install -r requirements.txt"

### ISSUE THREAD

**Issue by rlafuente** [shoebot/shoebot#209]
Okay, so doing a fresh install on a virtualenv, I was hit by this:

```
  Could not find a version that satisfies the requirement cairo>=1.17.0 (from -r requirements.txt (line 1)) (from versions: )
No matching distribution found for cairo>=1.17.0 (from -r requirements.txt (line 1))
```

Looked it up and the package seems to be named `pycairo` -- changing that line fixed the problem. I'm not sure this change is right so I'm putting this to get a confirmation from @stuaxo

**Comment by rlafuente** [comment]
...of course, to install I should have done `python setup.py install` and the error popped up because i did out of habit `pip install -r requirements.txt`, this makes me wonder why we have `requirements.txt` there?

**Comment by stuaxo** [comment]
Yeah, I don't think we do, feel free to make a patch to remove them.

**Comment by stuaxo** [comment]
Deleted - I don't think we have any docs that mention these.
