### ISSUE TITLE
1.3.1 release

### ISSUE THREAD

**Issue by stuaxo** [shoebot/shoebot#216]
This release will be a bugfix for a typo in setup.py

The other small feature I'd like to add is `--example-dir` (output directory examples are installed to), to aid scripting.

Let's see if we can shake out any more bugs.
I'm sure there will be some other small additions / fixes.

Definitely +1 on waiting about a week.

**Comment by rlafuente** [comment]
Done!

**Comment by stuaxo** [comment]
Great... I think we can do 1.4 for python3 support, and the code reorg if it's ready.

**Comment by rlafuente** [comment]
Agree!
