### ISSUE TITLE
IDE: clicking "Save" does not save -- instead deletes the file

### ISSUE THREAD

**Issue by rlafuente** [shoebot/shoebot#218]
This is a pretty serious one :-(

When clicking "Save", the file is instead silently deleted, with no UI feedback.

To debug, I removed the stdin and stderr redirections to see the tracebacks, and this is the error popping up:

```
Traceback (most recent call last):
  File "/home/rlafuente/.virtualenvs/shoebot/local/lib/python2.7/site-packages/shoebot-1.3-py2.7.egg/shoebot/ide/ide.py", line 566, in on_save_file
    self.save()
  File "/home/rlafuente/.virtualenvs/shoebot/local/lib/python2.7/site-packages/shoebot-1.3-py2.7.egg/shoebot/ide/ide.py", line 803, in save
    chars = self.get_slice(start, end, False)
AttributeError: 'ShoebotEditorWindow' object has no attribute 'get_slice'
```

Any idea @stuaxo? Maybe the GTKWindow interfaces changed and there's now an alternative to `get_slice`

**Comment by stuaxo** [comment]
That looks like it should be `buffer.get_slice(...)` instead of `self.get_slice(...)`.

**Comment by stuaxo** [comment]
(looks like a casualty of my refactoring - mailed you some detail).

**Comment by rlafuente** [comment]
Yup, `buffer.get_slice()` did the trick!

**Comment by stuaxo** [comment]
Great :)
