### ISSUE TITLE
Export functionality [NODEBOX PAGENUM]

### ISSUE THREAD

**Issue by stuaxo** [shoebot/shoebot#221]
Shoebot should have provide export functionality, to easily do things like create videos.

**Comment by vanderaalle** [comment]
Originally Nodebox1 allowed to refer in the code to the variable PAGENUM.
https://www.nodebox.net/code/index.php/Variables
PAGENUM: the current page being exported in a multi-page export.
In this way you can use PAGENUM value to address a certain behavior depending on the export number.
If you export five rendering, PAGENUM will be 1 in the first, 2 in the second and so on.

**Comment by stuaxo** [comment]
I don't have nodebox1 to hand right now.

How do you actually perform the export, is it from the GUI or a command ?
What kind of settings can you change ?

**Comment by vanderaalle** [comment]
From GUI, File menu, export, then from the pop up window you select how many files you want to render. For each rendered file, PAGENUM is updated. No other settings.

**Comment by vanderaalle** [comment]
hi just chiming in to say I had a really good experience with my first serious project in algorithmic plotting with shoebot. As a module from Python. And yes, by using different instances I can export different pdfs from the same script

**Comment by vanderaalle** [comment]
[alaiTebo-a.pdf](https://github.com/shoebot/shoebot/files/3513045/alaiTebo-a.pdf)

**Comment by stuaxo** [comment]
Hi,
   I just found this again, the plot looks nice - are you plotting beats per minute in there ?

S

**Comment by vanderaalle** [comment]
Hi, I'm plotting using a 16th value a sample rate. Data come from custom spectral analisys.
I'm then translating them into music notation.
https://soundcloud.com/vanderaalle/sets/selva-petrosa

**Comment by stuaxo** [comment]
Nodebox can also export animations, this page shows the export gui
https://www.nodebox.net/code/index.php/Animation.html

![image](https://user-images.githubusercontent.com/179677/80912989-e18caf80-8d38-11ea-8032-d91c237b8ca3.png

Which is based off PyQtSequence
http://undefined.org/python/#PyQTSequence

Which takes images then encodes videos.

Implementing this is probably dependent on fixing up our lifecycle + rendering to be a little less complex.

**Comment by stuaxo** [comment]
I spent some time to understand Nodebox1s runner, and it turns out it just sets PAGENUM to FRAME.

In the slightly more messy codebase here, I've done the same thing, so I can close this.

Note:  because of https://github.com/shoebot/shoebot/issues/247 the output might not be correct though.

Once #247 is fixed Shoebot 1.4 will be released.
