### ISSUE TITLE
ctrl-s does not work for me in the `shoebot` editor

### ISSUE THREAD

**Issue by aoloe** [shoebot/shoebot#228]
both ctrl-s and cltr-shift-s do not work on a new file.

the menu entry "save" does not work either for a new file.

`file > save as` does work.

**Comment by rlafuente** [comment]
After testing, it seems to create a file named `Untitled`, can you confirm this?

Just to be sure we're looking at the same behavior. I can then add a check to open Save As if it hasn't been yet saved.

**Comment by aoloe** [comment]
yeah, in the directory from where i started shoebot there are a `Untitled` and an `Untitled~` files... so your analysis might be right.

and, yes, calling Save As instead would be the right thing to do.

**Comment by stuaxo** [comment]
Fixed, in master.
