### ISSUE TITLE
colorMode doesn't work inside setup

### ISSUE THREAD

**Issue by azbulutlu** [shoebot/shoebot#233]
not sure if this is intended behavior
```python
def setup():
    colormode(HSB)
    size(500,500)
    background(1,0,1)
```
colormode simply gets ignored inside the function. On outside it works

**Comment by stuaxo** [comment]
Thanks, definitely a bug - colormode should be persistent.

**Comment by rlafuente** [comment]
This probably is related to the run-3-times bug (#247), see the output there

**Comment by stuaxo** [comment]
Closing as a dupe of #247
