### ISSUE TITLE
macOS 10.14  install issues from LGM

### ISSUE THREAD

**Issue by eliheuer** [shoebot/shoebot#241]
Following the install instructions [here](https://shoebot.readthedocs.io/en/latest/install.html) I ran into some issues on macOS 10.14.

Note: I was using a plain virtualenv and the shoebot master branch.

1. `pip install -r requirements.txt` as suggested by the readme didn't work because the requirements.txt file was missing from the repo.

2. I then cd'ed into the install directory and ran the install script with `./install_dependencies.sh`.

3. Then I did `python setup.py install` but got an error `Package 'libffi', required by 'gobject-2.0', not found`.

4. Then I did `brew install libffi` to try and fix this.

5. Now I get a new error: `No local packages or working download links found for pycairo>=1.17.0`.

6. Then I did `export PKG_CONFIG_PATH=/usr/local/Cellar/libffi/3.2.1/lib/pkgconfig` & `pip install pycairo`.

7. Now I get the error `No package 'gobject-introspection-1.0' found`.

8. Then I did `brew install gobject-introspection`.

9. Now I got `ValueError: Namespace GtkSource not available`

10. Gave up :-)

**Comment by rlafuente** [comment]
How about `brew install gtksourceview3`?

**Comment by eliheuer** [comment]
@rlafuente That did it, thanks!
![shoebot](https://user-images.githubusercontent.com/5162664/58751532-9b1a3b00-846d-11e9-9728-2ec3790b8597.png)

**Comment by rlafuente** [comment]
This is so good, seeing it work on a Mac got me really excited :-)

I've updated the dependency install script and the OSX install docs. I did not include the `export PKG_CONFIG_PATH` part as I wasn't sure if that step is required -- if you have the time to try out a fresh install with the updated scripts, that would be excellent!

**Comment by stuaxo** [comment]
@rlafuente any chance of adding macos to the travis script ?

I get shoebot working on macos about every 5 years and then it breaks because I don't try it.

**Comment by stuaxo** [comment]
Hi all,

MacOS has been added to travis, including tests that verify the install script, so when it comes to the version in master on git, I think we are in a pretty good place with homebrew now.
