### ISSUE TITLE
Mint 19.3 install problems / Conversation on API improvement

### ISSUE THREAD

**Issue by abixadamj** [shoebot/shoebot#253]
I just found this project - is great.
My system is:
```
adasiek@mint-desktop:~/shoebot-master$ lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 19.3 Tricia
Release:	19.3
Codename:	tricia
adasiek@mint-desktop:~/shoebot-master$ uname -a
Linux mint-desktop 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
adasiek@mint-desktop:~/shoebot-master$ python
Python 2.7.17 (default, Nov  7 2019, 10:07:09) 
[GCC 7.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
adasiek@mint-desktop:~/shoebot-master$ python3
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 

```
I tried to make install using infos from page: https://semestriel.framapad.org/p/shoebot

```
adasiek@mint-desktop:~$ cd shoebot-master/
adasiek@mint-desktop:~/shoebot-master$ python2 -m virtualenv venv
New python executable in /home/adasiek/shoebot-master/venv/bin/python2
Also creating executable in /home/adasiek/shoebot-master/venv/bin/python
Installing setuptools, pip, wheel...
done.
adasiek@mint-desktop:~/shoebot-master$ python2 -m virtualenv venv
New python executable in /home/adasiek/shoebot-master/venv/bin/python2
Not overwriting existing python script /home/adasiek/shoebot-master/venv/bin/python (you must use /home/adasiek/shoebot-master/venv/bin/python2)
Installing setuptools, pip, wheel...
done.
adasiek@mint-desktop:~/shoebot-master$ python2 setup.py install
setup options: 
with_pgi:       no

setuptools>=18.8
pycairo>=1.17.0
meta==1.0.2
Pillow>=6.0.0
pubsub==0.1.2
pygobject>=3.32
WARNING: The wheel package is not available.
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python2 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-CvKOvG/pycairo/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-CvKOvG/pycairo/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-u6RgDV
       cwd: /tmp/pip-wheel-CvKOvG/pycairo/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for pycairo
ERROR: Failed to build one or more wheels
Traceback (most recent call last):
  File "setup.py", line 189, in <module>
    test_suite="tests.unittests",
  File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 144, in setup
    _install_setup_requires(attrs)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 139, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 721, in fetch_build_eggs
    replace_conflicting=True,
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 777, in fetch_build_egg
    return fetch_build_egg(self, req)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/installer.py", line 130, in fetch_build_egg
    raise DistutilsError(str(e))
distutils.errors.DistutilsError: Command '['/usr/bin/python2', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpQsTSHe', '--quiet', 'pycairo>=1.17.0']' returned non-zero exit status 1

```

**Comment by rlafuente** [comment]
Hi! Thank you for trying this out and filing an issue, this really helps our efforts :-)

Those install instructions are outdated, many things have been changed -- particularly a move to Python 3. If you're running from master (as you seem to be), Shoebot needs Python 3.

Did you see the [install details](https://shoebot.readthedocs.io/en/latest/install.html#local-install-using-virtualenvwrapper) in the official docs?

**Comment by abixadamj** [comment]
@rlafuente - Thank for info. I want to use Shoebot in schools in Poland. I teach teachers in Poland (https://python.szkola.pl) 
I'm glad to heare that you move to Python3. I want to help with Shoebot, I will do PL translation and try to help with dev.

**Comment by abixadamj** [comment]
@rlafuente :+1: 

`sudo python3 setup.py install`
And works ;-)

![Zrzut ekranu z 2020-01-04 18-11-07](https://user-images.githubusercontent.com/5088643/71769154-99da5080-2f1d-11ea-8c43-4d1f888d508a.png)

**Comment by abixadamj** [comment]
OK, I have:
`/usr/local/lib/python3.6/dist-packages/shoebot-1.3.1-py3.6.egg`
GUI works.
But - I want to have also standard module to import in IDLE - is it possible?

**Comment by abixadamj** [comment]
I have:

'''
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license()" for more information.
>>> import shoebot
bot = shoebot.create_bot()
>>> bot.size(300,200)
>>> bot.rect(10,10,100,100)
<shoebot.data.bezier.BezierPath object at 0x7fa8bce5af60>
>>> bot.show()
Traceback (most recent call last):
  File "<pyshell#11>", line 1, in <module>
    bot.show()
  File "/usr/local/lib/python3.6/dist-packages/shoebot-1.3.1-py3.6.egg/shoebot/grammar/bot.py", line 373, in show
    self.snapshot(surface)
  File "/usr/local/lib/python3.6/dist-packages/shoebot-1.3.1-py3.6.egg/shoebot/grammar/bot.py", line 339, in snapshot
    self._canvas.snapshot(surface, defer)
NameError: name 'surface' is not defined
'''
Any idea, what I do wrong? I woud like to show output in window, like in shoebot-gui.

**Comment by stuaxo** [comment]
That looks like a bug, can you try editing line 339 on in
`/usr/local/lib/python3.6/dist-packages/shoebot-1.3.1-py3.6.egg/shoebot/grammar/bot.py`

and change the word `surface` to `target`, and less know if it works ?

**Comment by stuaxo** [comment]
I had a peek at the history in git and this is the right fix, so have committed this fix.

**Comment by stuaxo** [comment]
You can use the [shoebot as a module example](https://shoebot.readthedocs.io/en/latest/advanced.html#using-shoebot-as-a-python-module) in IDLE to generate image files:

```python
import shoebot

# set up a canvas
bot = shoebot.create_bot(outputfile="output.svg")

# size() needs to be called first
bot.size(400,400)

# now we can draw!
bot.rect(10,10,100,100)

# finish() should be called after all drawing commands
bot.finish()
```

Getting a shoebot window to show up when used as a module isn't directly supported, but can be done by wiring together enough of the internals:

```python
import time
import shoebot

# set up a canvas
bot = shoebot.create_bot(window=True, title="Shoebot from a module.")

frame = 0

while bot.canvas.sink.get_window():  # run until window is closed.
    # clear window ready for drawing
    bot.canvas.flush(frame)

    # bot code
    frame +=1

    bot.size(400,800)
    bot.fill(0, 0, 0.5)
    bot.rect(50,50,100,100)

    bot.rotate(frame / 2.)

    # update the shoebot window, the same as Gtk.main_iteration():
    bot.canvas.sink.main_iteration()

    time.sleep(0.1)  # wait between frames
```

Some things don't work (e.g. bot.FRAME does not iterate).

`show` may be the right API to for this work, currently it outputs images when run from inside a Jupyter notebook.

**Comment by abixadamj** [comment]
@stuaxo 
Works!
![Zrzut ekranu z 2020-01-06 19-39-07](https://user-images.githubusercontent.com/5088643/71839803-50743780-30bc-11ea-9831-d34f9f3734d2.png)

**Comment by abixadamj** [comment]
![Zrzut ekranu z 2020-01-06 19-42-43](https://user-images.githubusercontent.com/5088643/71840028-cd9fac80-30bc-11ea-8f62-f613e295a7f7.png)

**Comment by stuaxo** [comment]
You can see a window with the second version (I think on Linux it doesn't get quite as far), but things like the right click menu don't work without extra work - this may be fine though.

**Comment by stuaxo** [comment]
I'd like to improve API for use as a module, let me know what you think would be useful.
Running code in a window, and running a single frame are two things where the API could be more helpful.

**Comment by rlafuente** [comment]
Seconding this. I'm really happy to see that windowed mode works like this, and would also love to see a simpler syntax to get that working.

**Comment by stuaxo** [comment]
I was thinking along these lines
```python
def draw(bot):
    bot.rect(0, 0, 100, 100, 100)

bot.run(draw=draw)
```

or 

```python
@shoebot.draw
def draw(bot):
    bot.rect(0, 0, 100, 100)

bot.run()
```

The decorators idea is roughly based on Pyglet, though I need to remind myself what their ones look like.

`nodebox` and `nodebox-gl` are good sources for APIs we don't have yet, I think there might be handy things like `stop()` which may be how we quit.

Other things that need exposing / simplifying are functionality to "draw one frame", "delay until frame is due".

**Comment by abixadamj** [comment]
In my opinion (based on working with teachers) - decorator is very BAD idea (too complicated).
If we could do:
'''
bot = shoebot(destination=screen)
bot.rect(0, 0, 100, 100, 100)
bot.run()
'''
I know - maybe it is not 100% pure python way - I think using `with` statement would be good idea.

**Comment by stuaxo** [comment]
The above code is fine, but there is no way to animate it.

When you are not running shoebot as a module you can make animations with a draw function, that is called every frame:

```python
def draw():
    print("draw frame: ", FRAME)
    rotate(FRAME / 10.)
    rect(-40, -40, 80, 80)
```

nodebox.gl has something like:

```python
def draw(canvas):
   ...

nodebox.run(draw)
```

Fair enough, on  the decorator, I guess extra symbols are confusing ?
Their way of having code run every frame looks like:

```python
@window.event
def on_draw():
    window.clear()
    label.draw()
```

It seems python-y enough to me, (depending on what `screen` is).

**Comment by villares** [comment]
I'm on Xubuntu, not Mint, but `sudo python3 setup.py install` didn't work for me:

```
setup options: 
with_pgi:       no


setuptools>=18.8
pycairo>=1.18.1
meta==1.0.2
Pillow>=6.0.0
pubsub==0.1.2
pygobject>=3.32.1
ERROR: Failed to build one or more wheels
Traceback (most recent call last):
  File "/home/villares/.local/lib/python3.6/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
    subprocess.check_call(cmd)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmprillf1pz', '--quiet', 'pycairo>=1.18.1']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 189, in <module>
    test_suite="tests.unittests",
  File "/home/villares/.local/lib/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
    _install_setup_requires(attrs)
  File "/home/villares/.local/lib/python3.6/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/home/villares/.local/lib/python3.6/site-packages/setuptools/dist.py", line 721, in fetch_build_eggs
    replace_conflicting=True,
  File "/home/villares/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 783, in resolve
    replace_conflicting=replace_conflicting
  File "/home/villares/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1066, in best_match
    return self.obtain(req, installer)
  File "/home/villares/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1078, in obtain
    return installer(requirement)
  File "/home/villares/.local/lib/python3.6/site-packages/setuptools/dist.py", line 777, in fetch_build_egg
    return fetch_build_egg(self, req)
  File "/home/villares/.local/lib/python3.6/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
    raise DistutilsError(str(e))
distutils.errors.DistutilsError: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmprillf1pz', '--quiet', 'pycairo>=1.18.1']' returned non-zero exit status 1.
```

**Comment by abixadamj** [comment]
try to do:

```
$ sudo -i
# python3 setup.py install
```

**Comment by villares** [comment]
Thank you so much for the attention @abixadamk. I'll try this when I get the chance.

At this point I got it working by following the framapad's Ubuntu instructions!

**Comment by stuaxo** [comment]
I'm moving conversation around improving the API to run bots to #297

**Comment by stuaxo** [comment]
Closing, as it seems like the install issues were sorted.

Next release should make it easier and remove some of the need for sudo.
