### ISSUE TITLE
MacOS 10.11.6 install issues

### ISSUE THREAD

**Issue by villares** [shoebot/shoebot#255]
On Mac OS, after trying `pip3 install shoebot`and struggling with `gobject` and things I don't understand I then tried downloading the repository and running `install_dependencies.sh`. Didn't work.

Now I tried `sudo python3 setup.py install` and it gave no error messages!
-> [results](https://gist.github.com/villares/9b36878ab3deb1f49dd0aa722b37293f)

But `shoebot`on the terminal prints this:
```
Traceback (most recent call last):
  File "/usr/local/bin/shoebot", line 5, in <module>
    from shoebot.ide.ide import main
  File "/usr/local/lib/python3.7/site-packages/shoebot/__init__.py", line 36, in <module>
    from shoebot.core.backend import cairo
  File "/usr/local/lib/python3.7/site-packages/shoebot/core/__init__.py", line 38, in <module>
    from canvas import Canvas
ModuleNotFoundError: No module named 'canvas'
$ python3 shoebot
/opt/local/bin/python3: can't find '__main__' module in 'shoebot'
$ shoebot
Traceback (most recent call last):
  File "/usr/local/bin/shoebot", line 5, in <module>
    from shoebot.ide.ide import main
  File "/usr/local/lib/python3.7/site-packages/shoebot/__init__.py", line 36, in <module>
    from shoebot.core.backend import cairo
  File "/usr/local/lib/python3.7/site-packages/shoebot/core/__init__.py", line 38, in <module>
    from canvas import Canvas
ModuleNotFoundError: No module named 'canvas'
```
I tried `pip3 install canvas` now it complains about `cStringIO`:

```
Traceback (most recent call last):
  File "/usr/local/bin/shoebot", line 5, in <module>
    from shoebot.ide.ide import main
  File "/usr/local/lib/python3.7/site-packages/shoebot/__init__.py", line 36, in <module>
    from shoebot.core.backend import cairo
  File "/usr/local/lib/python3.7/site-packages/shoebot/core/__init__.py", line 38, in <module>
    from canvas import Canvas
  File "/usr/local/lib/python3.7/site-packages/canvas.py", line 5, in <module>
    from cStringIO import StringIO
ModuleNotFoundError: No module named 'cStringIO'
```

Thanks for making **shoebot**! I hope this might help somehow fixing Mac OS support.

**Comment by stuaxo** [comment]
The second import error is misleading.    Canvas is internal to Shoebot, I can see how the error lead you to try `pip install canvas`.

I would remove the `canvas` library you installed as this is triggering the `cStringIO` import error - that library doesn't support python 3 properly.

I'll try this under MacOS the next opportunity I get and try to reproduce your bug.

Let us know which things you didn't understand and we can try and improve our docs or install process.

**Comment by stuaxo** [comment]
Hi,
   I had a go in Mac OS 10.14 (as that was what my VM has).  And made the script hopefully a little more friendly.

At some point I had it installed, but the window would not come to the front - if that happens you may need to find the window + click on it when you run it.

I haven't been able to reproduce that since updating my homebrew packages though.

I let you know if I manage to run through everything successfully.

In the meantime - try removing the canvas package you installed, and try running the newer install script.

Make sure to use `python3` everywhere the docs mention `python`.

**Comment by stuaxo** [comment]
Apologies I haven't found time to try this in an earlier macos, any idea if the earlier changes fixed it ?

**Comment by villares** [comment]
I uninstalled, reinstalled with `pip3 install shoebot`
- no errors during install
- typing `shoebot` in the terminal doesn't work (traceback error message similar to the one reported)

Uninstalled with pip3, cloned the repo, pointed terminal to it and tried `sudo python3 setup.py`
- no errors during install
- I can't find `shoebot`
- tried `shoebot_clone/shoebot/run.py` but I guess this expects a file
- tried  `shoebot_clone/ide/ide.py` and it didn´t work

I guess I have no idea of what I'm doing, but then, most beginners might be like me... :)

**Comment by stuaxo** [comment]
Thanks, this is all useful info.

Sometimes if you things don't appear in the path after you install running `hash -r` in the commandline can help.

If you need a file then any of the ones in `examples` will do, I normally use `examples/animation/hypnoval.bot`.


You can try installing as a user (without sudo), like this:

`python3 -mpip install -e .`

Can you try running

```shell
python3 setup.py diagnose
python3 setup.py test
```

(you might need to try with python3) and see what the output is ?

There is also a bug sometimes in macos where the window opens but is in the background, I haven't been able to reproduce it yet though.

**Comment by villares** [comment]
Cheers!

`shoebot/run.py examples/animation/hypnoval.bot`
Result:
```
Traceback (most recent call last):
  File "shoebot/run.py", line 251, in <module>
    main()
  File "shoebot/run.py", line 229, in main
    from .__init__ import run  # https://github.com/shoebot/shoebot/issues/206
ImportError: attempted relative import with no known parent package
```

python3 setup.py diagnose
https://gist.github.com/villares/59db3cfe0f0a6b0f6a51e240b3184b26

python3 setup.py test
https://gist.github.com/villares/8b6e9704f4b42649a41ab15e81101ce6

**Comment by stuaxo** [comment]
Thanks.

I think it's installed OK, but `sbot` and `shoebot` are not in the PATH somehow.

You might have some luck running them this way:

sbot:
`python3 -mshoebot.run`
`python3 -mshoebot.run examples/animation/hypnoval.bot

shoebot (ide):
`python3 -mshoebot.ide.ide`

Or try and add the binaries directory to the PATH.
I'll try and add some extra info to `diagnose` to detect this situation and suggest a fix.

**Comment by villares** [comment]
Hi @stuaxo thank you for all the effort!
I have tried `python3 -mshoebot.ide.ide` and the result was this:

```
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/shoebot-1.3.1-py3.7.egg/shoebot/ide/ide.py", line 15, in <module>
    gi.require_version('GtkSource', '3.0')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PyGObject-3.34.0-py3.7-macosx-10.11-x86_64.egg/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GtkSource not available
```

**Comment by stuaxo** [comment]
It looks like you don't have gtksourceview3 installed you can try: `brew install gtksourceview3`.
(or try and run the install-dependencies.sh script again and post any errors).

It looks like the binaries installed to:
`/opt/local/Library/Frameworks/Python.framework/Versions/3.7/bin`

If you add it to your PATH you should be able to run `sbot` and `shoebot`.

**Comment by villares** [comment]
Amazing how hard simple things can be, `sudo nano /etc/paths` and added `/opt/local ... /bin` hasn't worked yet.

I tried `install-dependecies.sh` again and it failed exactly a gtksourceview3 dependency: netpbm 

Now I'm trying to solve `netpbm` using this information: https://github.com/octave-app/octave-app/issues/121 it takes a loooong time... will post back. :D

**Comment by stuaxo** [comment]
Good luck, keep a note of what you do and we can update the docs.

I just read that and saw its 10.11 only, unfortunately OSX KVM which I use to test OSX doesnt let me install that version so I can't test it myself :(

This reminds me, we should probably add OSX to travis finally.

**Comment by villares** [comment]
One more thing... so I tried `pip3 install shoebot` again, it did not complain and it seems to have added shoebot to the PATH. Now... if I type `shoebot` I get this:
```
Traceback (most recent call last):
  File "/usr/local/bin/shoebot", line 5, in <module>
    from shoebot.ide.ide import main
  File "/usr/local/lib/python3.7/site-packages/shoebot/__init__.py", line 36, in <module>
    from shoebot.core.backend import cairo
  File "/usr/local/lib/python3.7/site-packages/shoebot/core/__init__.py", line 38, in <module>
    from canvas import Canvas
ModuleNotFoundError: No module named 'canvas'
```
Note that nothing changed in terms of `python3 -mshoebot.ide.ide` as described in the last comment (same `ValueError: Namespace GtkSource not available` message)

**Comment by stuaxo** [comment]
What a pain, good work getting this far !  
Linux is easier with the libraries used than OSX.

The last message in the brew output suggests reinstalling gtksoureview3, so try that:

`brew reinstall gtksourceview3`

Then -

The version of shoebot on pypi is a little behind this one (I just noticed in git it's `from .canvas import` not `from canvas import` < notice the dot.

Try uninstalling:  `pip uninstall shoebot`, then install this version.

In the shoebot directory run

`pip install -e .`

Then ... we might be good 💥💥💥💥

**Comment by villares** [comment]
`pip3 uninstall shoebot` 
followed by 
`pip3 install -e .`
used inside the cloned folder
💥💥💥💥
success!

**Comment by stuaxo** [comment]
Awesome !!

I reckon this is a sign we need a new release on pypi soon so that `pip install shoebot` has a better chance of working.
