### ISSUE TITLE
Implement path.difference in bezierpath

### ISSUE THREAD

**Issue by stuaxo** [shoebot/shoebot#26]
Nodebox uses Generic Polygon Clipper for this [ http://www.cs.man.ac.uk/~toby/gpc/ ].

**Comment by rlafuente** [comment]
Really sad to see the license is incompatible, but this is really not an option for us.

[Shapely](https://shapely.readthedocs.io/en/latest/) looks promising, though!

**Comment by rlafuente** [comment]
Moving discussion #166
