### ISSUE TITLE
`import shoebot` question/issue

### ISSUE THREAD

**Issue by villares** [shoebot/shoebot#265]
I have shoebot IDE running nicely on Xubuntu 18.0

but when I try `import shoebot` in Python I get this message:

```
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import shoebot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/villares/shoebot/shoebot/__init__.py", line 47, in <module>
    from shoebot.core.events import publish_event, QUIT_EVENT
  File "/home/villares/shoebot/shoebot/core/events.py", line 7, in <module>
    import pubsub
  File "/home/villares/.local/lib/python3.6/site-packages/pubsub.py", line 98
    count[channel] = 0L
                      ^
SyntaxError: invalid syntax
```

Any suggestions/ideas of what is going on? Am I doing something wrong?
I have tried both in the REPL and in a .py file.

**Comment by stuaxo** [comment]
It looks like the version of pubsub needs bumping, this is fixed in shoebot on git.

Install pubsub in the same way as you installed shoebot, i.e. if you installed shoebot with `pip install shoebot` do the `pip install pubsub`.

If you installed shoebot using `sudo` then use sudo.

**Comment by stuaxo** [comment]
Otherwise you can edit

`"/home/villares/.local/lib/python3.6/site-packages/pubsub.py"`

And change this line:  `count[channel] = 0L`   to remove the `L`.

**Comment by villares** [comment]
Uninstalled and re-installed `pubsub` and it worked! Yay!

**Comment by stuaxo** [comment]
Great :)

Thanks for reporting everything you find, its really handy for the next release.
