### ISSUE TITLE
Release shoebot 1.4.0

### ISSUE THREAD

**Issue by stuaxo** [shoebot/shoebot#266]
Ticket about releasing 1.4.0 - many bugfixes + OSX now fixed.

Blocking issues (must have):
  ~~#264~~ ~~#265~~ ~~#274~~  ~~#275~~  ~~#277~~ ~~#283~~ ~~#285~~ ~~#287~~ ~~#289~~ ~~#312~~ #247 #322

Not as important issues (should have):
~~#288~~ ~~#290~~  #291  #315  #296

Outstanding from previous release (could have) ~~#202~~
#155 

EDITED, original text below:
> 
> We need a bugfix release because one of our dependencies for 1.3.1 was not bumped to the python3 compatible version.
> ~~https://github.com/shoebot/shoebot/issues/265~~
> 
> If running under python3.x - and people should only be running under 3.x now.
> 
> Non bugfixes:  
> The SVG output bugfix is unlikely to be fixed as it's too difficult.
> 
> Other nice to haves:
> 
> This fix to get OSX into travis should land:
> ~~https://github.com/shoebot/shoebot/pull/264~~
> 
> Should probably add some minimal docs about shoebots unittesting infrastructure as thats the most important new thing.
> 
> Info / screenshots about shoebot in Jupyter is probably worthwhile too.

**Comment by stuaxo** [comment]
List of changes since v1.3.1 tag:

Docs:
- Recommends per-user install, not system-wide.
- Update many documentation references from python to python3.

Install Script:
- Update homebrew support in Install script.
- Add homebrew to travis.
- Add options to the install script: help. output which packages will be installed.

Testing:
- Added missing packages to travis for homebrew and ubuntu.
- Added checks to ensure travis and the install script are consistent
- Update unit tests to use AAA and be more sensible.
- Add end to end tests to start check visual output of some examples
- Add OSX support to end to end tests.

Libraries:
- Port various bits to pyrhon3 + remove python3isms.
- Cleanups and reformatting (including the colours library inherited from Nodebox)
- Fixes in the graph example and library
- SBVideo alert the user if numpy is not installed

**Comment by rlafuente** [comment]
I can do this over the weekend, is there any leftover task before packaging?

(i can take care of that TODO re: setup, changelog and pypi)

**Comment by stuaxo** [comment]
I'll try running all the examples and see if there is anything I can come up with.

I haven't had time to test installing on anything other than OSX and Ubuntu, I'm pretty sure the package lists in `install/install_dependencies.sh` are not as complete as those two OS's and may be out of date (especially Fedora/Redhat/SUSE).

**Comment by stuaxo** [comment]
Mostly just try and find as many broken things as possible,  I found a python2ism that breaks doc generation just now.

I've only tested OSX (and just one version) and Ubuntu so far.

I guess the things I'm aware of are closest to what I already looked at, e.g. I'm sure the package lists for other distros may be out of date and are definitely not as complete as ubuntu and homebrew.

**Comment by stuaxo** [comment]
Let's hold off releasing for now, I'm sure there's more to find over the next few days.

**Comment by stuaxo** [comment]
@rlafuente the big change here for users, is I've changed the docs to recommend installing without sudo, so it's worth testing if that breaks in any way.

**Comment by stuaxo** [comment]
Bumped number since there are a lot of fixes already and a few more to go.

**Comment by rlafuente** [comment]
I started #397 to put the newer stuff from the last months in and cleanup after all this time. We can move the discussion there?
