### ISSUE TITLE
Read/load existing SVG

### ISSUE THREAD

**Issue by hellocatfood** [shoebot/shoebot#276]
Is it possible to read an existing SVG into Shoebot? I'd like to be able to modify the objects, paths, and their nodes.

**Comment by stuaxo** [comment]
Shoebot ships with the svg library from Nodebox.

There are some examples in `examples/svg`.

It looks like `go.bot` triggers a bug, but the other two examples work.

I'm going to look into fixing this + see if it's possible to make progress in getting the tests for that library working.

**Comment by stuaxo** [comment]
Just realised that `go.bot` is only on my machine.

There is a bug when Image is used with SVGs, this PR will fix https://github.com/shoebot/shoebot/pull/277

**Comment by stuaxo** [comment]
OK, the other branch is merged.

Now we're I'm adding tests I'm finding lots of things to fix :)
