### ISSUE TITLE
Port to gtk3

### ISSUE THREAD

**Issue by stuaxo** [shoebot/shoebot#28]
Gtk2 is deprecated, shoebot needs porting to Gtk3.

**Comment by stuaxo** [comment]
'pgi' branch is the state of the art on this, need to check the 'gtk3' branch and see if theres any thing that can taken from it

**Comment by tian2992** [comment]
Hi, is the typography support still broken on branch pgi?

**Comment by stuaxo** [comment]
Good question, I haven't tested this recently; last time I tried this IRCC PangoContext didn't work which put a bit of a spanner in the works.
And there was this bughttps://github.com/lazka/pgi/issues/13
  I seem to recall that .gi files that didn't work included 'interface' didn't work in .gi.
I found this going through old branches and trying to clean up.
If you could do some testing and find out what breaks it would be super useful.

The current state of the 'shoebot-gtk3-pgi' branch is up to date with master - I could probably make it work with standard gtk3 too. - The gtk3 branch itself is bitrotted, but I checked and I'd merged everything into gtk3.
My current idea is to get shoebot completely cleaned up, old branches all merged and look at a release - then work on something based on a new graphics API; which I could eventually maybe port shoebot to (though maybe in a python3 guise).
The current github state is pretty good, livecoding stuff is all merged, the old IDE works 
- I'm currently merging the nodebox color examples and copying the various bots I've worked on over the years and making everything easier to install.   
Shoebot is a great platform for prototyping graphics software; we should probably think about a release.   
The release that follows (on our usual timetable) will be the gtk3 version.
S++ 


     On Monday, April 20, 2015 1:19 AM, Sebastian Oliva <notifications@github.com> wrote:
   
 

 Hi, is the typography support still broken on branch pgi?

**Comment by stuaxo** [comment]
I'm thinking quite a lot about what a spiritual successor to shoebot should be like, so if you have any thoughts then this mailing list is a good place :) S++ 


     On Monday, April 20, 2015 2:09 AM, Stuart Axon <stuaxo2@yahoo.com> wrote:
   
 

 Good question, I haven't tested this recently; last time I tried this IRCC PangoContext didn't work which put a bit of a spanner in the works.
And there was this bughttps://github.com/lazka/pgi/issues/13
  I seem to recall that .gi files that didn't work included 'interface' didn't work in .gi.
I found this going through old branches and trying to clean up.
If you could do some testing and find out what breaks it would be super useful.

The current state of the 'shoebot-gtk3-pgi' branch is up to date with master - I could probably make it work with standard gtk3 too. - The gtk3 branch itself is bitrotted, but I checked and I'd merged everything into gtk3.
My current idea is to get shoebot completely cleaned up, old branches all merged and look at a release - then work on something based on a new graphics API; which I could eventually maybe port shoebot to (though maybe in a python3 guise).
The current github state is pretty good, livecoding stuff is all merged, the old IDE works 
- I'm currently merging the nodebox color examples and copying the various bots I've worked on over the years and making everything easier to install.   
Shoebot is a great platform for prototyping graphics software; we should probably think about a release.   
The release that follows (on our usual timetable) will be the gtk3 version.
S++ 


     On Monday, April 20, 2015 1:19 AM, Sebastian Oliva <notifications@github.com> wrote:
   
 

 Hi, is the typography support still broken on branch pgi?

**Comment by stuaxo** [comment]
Just realised this is on github + not the mailing list.

I did some further investigation, and it's the use of PangoCairo that breaks pgi here ... it's used for getting metrics, creating the layout + doing font to path which seem to be all of the interesting things to do with typography...   I guess I should make the branch work with plain 'gi.repository' as well.

I'm holding out for 'pgi' though, since it works with pypy and in virtualenvs out the box.

**Comment by stuaxo** [comment]
Hmm ... so using 'gi' seems to get a segfault for me on Ubuntu :/  if I can get past that I can do more testing.

In the meantime, try it on non-ubuntu with 'gi' it may work somewhat..

**Comment by stuaxo** [comment]
It turns out cairocffi might help here... fingers crossed ..

**Comment by stuaxo** [comment]
Ok, gonna keep bashing this until some text comes out in gtk3 ... then I could do with some help as it's the bit of shoebot I know least about.

**Comment by stuaxo** [comment]
This is now 'not crashing' the spacing stuff is commented out as I don't know how to do that in Gtk3 yet, also the text to path examples seem to not output anything, not sure whats going on there.

To test it - checkout the branch + create a virtualenv.

Inside the virtualenv:

- install gi and shoebot
$ pip install vext.gi
$ python setup.py install

.. run examples

- path stuff, no output yet
$ sbot -w examples/pathfilters/draft.bot

Not sure why it's returning empty paths, any input is welcome - I'm a bit weak on Pango ... otherwise, I'll need to find the time, to work out pango and just rewrite the typography bit starting from a pango example.

**Comment by stuaxo** [comment]
OK, this seems to work :)

I might even get merge it, if it works on Windows.    On pypy the typography stuff will have to wait for pgi to catch up.

**Comment by stuaxo** [comment]
Merged .. .could do with testing :)
