### ISSUE TITLE
Web library needs porting to python 3

### ISSUE THREAD

**Issue by stuaxo** [shoebot/shoebot#288]
It's trying to use urllib2

```
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "/tmp/shoebot-tmp/shoebot/grammar/bot.py", line 402, in ximport
    lib = __import__(libName)
  File "/tmp/shoebot-tmp/lib/web/__init__.py", line 35, in <module>
    from . import url
  File "/tmp/shoebot-tmp/lib/web/url.py", line 10, in <module>
    import socket, urllib, urllib2, urlparse
ModuleNotFoundError: No module named 'urllib2'Traceback (most recent call last):


During handling of the above exception, another exception occurred:
```

**Comment by stuaxo** [comment]
`web` itself looks like a bit of a mess, and hard to port.

A lot of the examples seem to use `URLAccumulator` (and one `HTTP403Forbidden`) from urls, so moving to requests, but porting `URLAccumulator` might take things quite a long way.

**Comment by rlafuente** [comment]
I think we can drop this lib; most of the supported API s are ancient and there's enough resources out there for scraping specific sites.

Maybe others have the same problem, and I'm for removing all cruft that we can!

On September 22, 2020 10:46:49 AM GMT+01:00, Stuart Axon <notifications@github.com> wrote:
>`web` itself looks like a bit of a mess, and hard to port.
>
>A lot of the examples seem to use `URLAccumulator` (and one
>`HTTP403Forbidden`) from urls, so moving to requests, but porting
>`URLAccumulator` might take things quite a long way.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/shoebot/shoebot/issues/288#issuecomment-696618257

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by stuaxo** [comment]
Cool, are you up for doing the patch to remove it?  Not sure I have the headspace for it at the moment :)

**Comment by rlafuente** [comment]
Done!

**Comment by karstenw** [comment]
If I remember correctly, the Pattern lib replaced the web lib in Nodebox. And the current one seems to be py3 only.
[https://github.com/clips/pattern](https://github.com/clips/pattern)

**Comment by stuaxo** [comment]
We don't need to include it, since it can be installed from pypi.

It might be good to have examples though, if there are existing nodebox examples we might be able to use those, or if there are examples for other versions of nodebox, e.g. nodebox-gl, we may be able to easily port them and include them.
