### ISSUE TITLE
Comments in IDE not legible

### ISSUE THREAD

**Issue by hellocatfood** [shoebot/shoebot#298]
I'm using Shoebot on Ubuntu 20.04. When using Shoebot IDE's built in dark theme comments are not legible. The blue against a dark background is hard to see.

![Screenshot from 2020-04-27 12-39-59](https://user-images.githubusercontent.com/151947/80368286-62a0fe00-8884-11ea-8487-13200af67c50.png)

**Comment by stuaxo** [comment]
Good spot :)

Let me know if you have other ideas about improvements about colours / fonts in the console output in this issue.

**Comment by stuaxo** [comment]
I need to look at how the IDE colours work, it looks like there are themes available:

https://wiki.gnome.org/Projects/GtkSourceView/StyleSchemes

**Comment by hellocatfood** [comment]
Great, I didn't know about that resource. Have you seen the styles that come with Gedit?

![Screenshot from 2020-04-27 15-04-59](https://user-images.githubusercontent.com/151947/80381738-49ef1300-8899-11ea-8f4a-345ab3594b1b.png)

From that the ones that work well with Python code are Cobalt, Kate, Oblivion, Solarized Dark (although comments look a bit to close to code), and Solarized Light.

I'll check out the other ones in that link.

**Comment by stuaxo** [comment]
I didn't know about that resource until I saw this bug :)

Hm, this list looks familiar...

![image](https://user-images.githubusercontent.com/179677/80386386-38a90500-889f-11ea-94b0-3aba04a9795a.png)

Maybe Cobalt for dark ?

It seems to be the closest to classic.

Ideally we'd have some sort of chooser, but I don't want to make any really big changes to the IDE until I've seperated it's code from the rest of Shoebot, which might take a bit longer ?

**Comment by stuaxo** [comment]
Work in progress..

![Peek 2020-04-27 20-43](https://user-images.githubusercontent.com/179677/80413864-08299100-88c8-11ea-8433-d880a77b90ea.gif)

**Comment by stuaxo** [comment]
Merged to master.
