### ISSUE TITLE
Shortcuts for Gedit plugin

### ISSUE THREAD

**Issue by hellocatfood** [shoebot/shoebot#308]
I've been using the gedit plugin for shoebot and find that it's long-winded to have to go to Menu > Tools > Shoebot > Run in Shoebot every time to run the script. Can there be a (user-definable) shortcut for this?

**Comment by hellocatfood** [comment]
It is possible to define a custom keyboard to run `sbot` by using the "Manage External Tools" plugin https://wiki.gnome.org/Apps/Gedit/Plugins/ExternalTools However, it doesn't seem possible to use the current document as an argument for it

**Comment by hellocatfood** [comment]
Apologies, I spoke too soon!

A shortcut can be defined using that plugin. Entering this worked:
`/usr/local/bin/sbot $GEDIT_CURRENT_DOCUMENT_NAME`

However, if having shortcuts predefined in the plugin is possible then it would negate the need for an external plugin.

**Comment by stuaxo** [comment]
I'll need to see how that plugin does shortcuts.

CTRL-R should already be the shortcut to run Shoebot, but that stopped working when Gedit changed its menu system.
I don't know why it's not working, although maybe it's as simple as Gedit is using CTRL-R for something else.

Try changing the value here to some other shortcut
https://github.com/shoebot/shoebot/blob/master/extensions/gedit/gedit3.12-plugin/shoebotit/__init__.py#L21
And reinstall the plugin.

The other things the shoebot plugin does are:

Have a menu of examples (only when shoebot is in the path).
Toggles for live coding, variables window, sockets.

If these can all be done using another plugin then that could work.

On the other hand:   switching to an external plugin would let us lose a lot of legacy code, so would be a +.

There are a lot of legacy things in Shoebot at this point, so I'm pretty keen about building a legacy free replacement that is easier for people to install and for me to maintain.

**Comment by stuaxo** [comment]
>  `/usr/local/bin/sbot $GEDIT_CURRENT_DOCUMENT_NAME`

Can you try, creating a new unsaved document and see if that works, and if it works, let me know what GEDIT_CURRENT_DOCUMENT_NAME, is?

**Comment by hellocatfood** [comment]
> Can you try, creating a new unsaved document and see if that works, and if it works, let me know what GEDIT_CURRENT_DOCUMENT_NAME, is?

Running this on an unsaved document first asks me to save a document. After that it runs. I got that variable name from here https://wiki.gnome.org/Apps/Gedit/Plugins/ExternalTools

**Comment by stuaxo** [comment]
Cheers, that's interesting.

I'll see if I can find out how it gets the shortcut keys + see if I can fix the plugin.

I think this relies on the file being saved, we don't do that, so we can support livecoding - we send new code to a running instance of shoebot.

BTW, Which keyboard shortcut are you using ?

**Comment by hellocatfood** [comment]
Actually, forget the last comment. I realised I had the plugin set to save the document upon running it. This is my current settings. 

![Screenshot from 2020-09-07 16-28-30](https://user-images.githubusercontent.com/151947/92402407-66dd0200-f127-11ea-890f-f937bf7d0b75.png)

I have the plugin shortcut set to Ctrl + Shift + R. I could also have just used Ctrl + R but for whatever reason I like to add the Shift in there.

**Comment by stuaxo** [comment]
Try the fix on this branch https://github.com/shoebot/shoebot/tree/gedit-3-12-re-enable-key-accels

You will need to reinstall the gedit plugin using the script at `extensions/gedit/install.py`.

**Comment by hellocatfood** [comment]
Yes, this works now :-)

**Comment by stuaxo** [comment]
Great, we're all sorted until they bring out GNOME 4, with a new Gedit and everything breaks again !
