### ISSUE TITLE
Update install_dependencies to include mingw64

### ISSUE THREAD

**Issue by stuaxo** [shoebot/shoebot#312]
With work from @speters33w https://github.com/shoebot/shoebot/issues/310 we managed to bring up shoebot on mingw64.

- [x] get minimum list of packages from issue #310, and verify install on a fresh mingw64
- [x] add to ./install/install_dependencies.sh
- [x] document that shoebot works on windows via mingw64

**Comment by speters33w** [comment]
I can do a clean install of msys2 mingw64 and update the package dependencies required and verification and update shoebot/doc/source/install.rst. I'm guessing at this time you want: Install msys2 64 bit and STRONGLY recommend default directory then; on msys2 pacman python-newest (currently 3.8.something) which has to be installed first; install gtk3 and pygobject; install gtksourceview; install git
THEN
$ git clone https://github.com/shoebot/shoebot
cd shoebot
python -mpip -e 

That's how you want people to install at this point, correct?

and add a quick note on how to associate .bot files to shoebot.

Are we safe saying "Shoebot runs on Python 2.8."? (was 2.7, mingw64 installs 2.8 and I think it's at least mostly working)

I'm kind of new to github, I'll fork project edit install.rst and create pull request? Is that how it works?

**Comment by speters33w** [comment]
I could also try my hand at the shell script that does all of the above once mingw64 is installed. 
I've never written one before - I've written a lot of DOS/Windows batch files - but I'd have to learn how to handle error processing, eg Internet craps out in the middle of one of the installs and download doesn't complete, package was pulled from repository, whatever script would have to stop and produce error message.

**Comment by stuaxo** [comment]
Luckily MINGW is close enough to what we already support that you can probably edit the existing script that works for Linux distros and OSX:

https://github.com/shoebot/shoebot/blob/master/install/install_dependencies.sh


It checks the OS then tries it install packages.

If I run it on ubuntu it'll use apt-get... on MingW it shows a message:

```
$ ./install/install_dependencies.sh
Shoebot does not directly support MINGW64_NT-10.0-19042 3.1.7-340.x86_64 at the moment.

Get started by looking at "Add support for another operating system".
in the installation documentation.
```

I'm not sure if the docs are good, but basically you'll want to add

`MINGW64_PACKAGES = ""`

At the top with the packages separated by spaces.

Then a bit further down there are functions for each kind of package manager, you'll probably want to add one for pacman on mingw64.

Then at the bottom, in the block that checks for OSs add one for MingW (for now just check "$OS" is equal to whatever string it outputs when you run it - it'll be MINGW64_NT-10.0-19042 or something similar) + have it call the new function.

If you get that working on a PR initially, then we can tweak it + land it.


Definitely +1 on a package at some point.

**Comment by stuaxo** [comment]
>  can do a clean install of msys2 mingw64 and update the package dependencies required and verification 

Great :)

> ... update shoebot/doc/source/install.rst. I'm guessing at this time you want: Install msys2 64 bit and STRONGLY recommend default directory 

:+1: 
> ...on msys2 pacman python-newest .... install gtk3 and pygobject; install gtksourceview; install git

^ hopefully ./install/install_dependencies.sh can be updated to do this bit.

> THEN
> $ git clone https://github.com/shoebot/shoebot

+1 on mentioning git in install.rst, it's not there right now.

> cd shoebot
> python -mpip -e
> 
> That's how you want people to install at this point, correct?
>

^ I think `python -mpip -e .` probably is better than `python setup.py install` currently in the docs, but don't feel too strongly on this.
 
> ... add a quick note on how to associate .bot files to shoebot.
> 
:+1:

> Are we safe saying "Shoebot runs on ~~Python 2.8."? (was 2.7, mingw64 installs 2.8 and I think it's at least mostly working)~~

3.8 .. works, I haven't tested 3.7 in a while, but I think that is probably still OK.

> 
> I'm kind of new to github, I'll fork project edit install.rst and create pull request? Is that how it works?

Yep, basically - you clone the project on github, then `git clone` it to your computer create a new branch to work on + push changes back and make a PR.


You might want to build the HTML docs locally to test your edits:

Install the dependencies:

```sh
cd docs
pip install -r requirements.txt
```

Then build docs:
```sphinx-build -b html -d build/doctrees source build/html```
The files are output into doc/build/html.  There are a few errors, this might just be mingw64 incompatiblity though.

To rebuild, you'll need to delete the `build` directory, then run again.

**Comment by speters33w** [comment]
There's still something wrong with pillow, but the rest installed great.

This is an exact sequence on a clean install. I have a backup right before the git clone, so it can be tried again after tweaks.

```
pacman -Syu
pacman -Su
pacman -S mingw-w64-x86_64-python
pacman -S mingw-w64-x86_64-gtk3 mingw-w64-x86_64-python3-gobject 
pacman -S mingw-w64-x86_64-gtksourceview3
pacman -S git
pacman -S mingw-w64-x86_64-python-pip
# switch to MinGW 64 bit
cd shoebot
python setup.py install #NOTE- It didn't like python -mpip -e
# !!!pillow - lots of warnings and tracebacks!!!
# switch back to MSYS SYS
pacman -S mingw-w64-x86_64-python-pillow
# switch back to MinGW 64 bit
cd shoebot
python setup.py install
```

SUCCESS!!!!!!
Here's the full log:

[Full_msys_clean_install.log](https://github.com/shoebot/shoebot/files/5948444/Full_msys_clean_install.log)

![shoebotworks](https://user-images.githubusercontent.com/25144507/107309983-7b685200-6a59-11eb-9e8e-1fb83aa4503d.png)

**Comment by stuaxo** [comment]
OK, great - can you try with all the pacman packages on one line, as that's the easiest way to integrate with the install script ?

It's going to be at least the evening UK time before I can look at anything in any detail.

**Comment by speters33w** [comment]
I was actually working on the shell script now. So far I've got the OS in
there, I had to put it after the else statement and use if "${OS:0:7}" =
'MINGW64" or "MSYS_NT" because of the two terminal type split and it
returns the windows version after the OS, which can vary a lot depending on
service pack level, etc.
I might have the shell script working and tested tonight New York time.
I've got a bunch of other household stuff to do for a few hours.

**Comment by stuaxo** [comment]
Awesome, no rush :)

The thing with Pillow seems to happen when GCC.exe is not in the PATH so it might be worth adding that to the instructions (but also include python the python-pillow msys package anyway).

https://github.com/python-pillow/Pillow/pull/4019

**Comment by speters33w** [comment]
Here's your shell script. **Verified works**. I went ahead and had it install pip and git even though they are not technically dependencies, those installs can be removed at package drop to the msys2 repository, or left in there.

[install_dependencies.sh.txt](https://github.com/shoebot/shoebot/files/5952434/install_dependencies.sh.txt)

**Comment by stuaxo** [comment]
The changes look good, does the `MSYS_NT` need a guard to display a message if people are running under 32 bit ?

**Comment by speters33w** [comment]
It would burp out on first install since python has required Win7 for a few
years since, I think, 3.0.

The one odd situation where it might need the guard is Win7 32 bit, which
is unusual. I have one I use to communicate with older PLC ladders, UPS
systems, etc. via -yes this is 2021- 9 pin serial or RS485 serial.

No, I won't be using it for Shoebot.

I might fire it up sometime this week and see what happens, though I don't
think you can even get a 32 bit msys2 installer directly anymore.

It has to have msys_nt because they recommend you use msys sys for
installing packages globally. Msys sys is pretty much bash, and doesn't
access the 64 bit bin directory, so you have to run the actual programs
we're installing from MinGW64.

msys2 requires Win7 to even install, if I remember right. I'm typing on my
phone or I would look it up.

**Comment by stuaxo** [comment]
Cheers, I always get confused about the distinction between MSys and Mingw.. 

In future you can imagine there being an ARM version too.

**Comment by stuaxo** [comment]
Fanastic, - I've committed your additions to the script :)

I added a guard to stop it running in MingW64-32 bit, as that seems to set the C compiler environment variables to be 32 bit which could cause issues.

You can pull the latest version using:

`$ git pull origin`

I fixed the bug in the Makefile that stops the docs generator working in MingW, so you can test any changes to the docs.


To generate docs:
```sh
cd docs
make clean
make html
```

The adding new OSs bit is a bit out of date (still mentioned Python2 when it should be Python3
![image](https://user-images.githubusercontent.com/179677/107453774-7c75ae00-6b43-11eb-9c79-f5dc48b9bec2.png)

And there's no header for IDE that needs GTKSourceView3

I can add these, but don't want to edits to conflict if you are changing stuff.

**Comment by speters33w** [comment]
Yeah, I'll be working on the install.rst

**Comment by speters33w** [comment]
Here's your rusty file... I fixed a couple other minor errors in it, too, for example Mac Homebrew was italicized instead of hyperlink, etc.

It built fine. I only got errors about unreadable pngs in commands.rst, but the pictures show up fine in the html.

[install.rst.txt](https://github.com/shoebot/shoebot/files/5955740/install.rst.txt)

**Comment by speters33w** [comment]
OOOOH!! I made a mistake in my instructions, and told the user to type: `./install/install_dependencies.sh` instead of `./install_dependencies.sh` after downloading the script into their home directory. 

Here's the corrected file, and I'll edit the above comment, to have the corrected file, too.

[install.rst.txt](https://github.com/shoebot/shoebot/files/5958394/install.rst.txt)

**Comment by stuaxo** [comment]
Nice, can you try and do the edit in github?  
It's easier to perfectly safe, and easier for me to manage (+ you get your name in the commits)
 :)

**Go to**
https://github.com/shoebot/shoebot/blob/master/install/install_dependencies.sh

**Click the pen:**
![image](https://user-images.githubusercontent.com/179677/107556666-9a3d2480-6bd0-11eb-9c23-18a68690e186.png)

**Then paste in your changes:**
![image](https://user-images.githubusercontent.com/179677/107556783-be990100-6bd0-11eb-8f81-35c69a2947aa.png)

**Scroll down + fill in the description**
![image](https://user-images.githubusercontent.com/179677/107557136-20f20180-6bd1-11eb-846d-4fb3bc59aee4.png)
Tick "create a new branch", and give it a name

The branch will be created in your own repo, if you need to make any other changes, you can edit it there (you don't need to a new branch then if you are still tweaking the PR).

**Comment by speters33w** [comment]
Sure.

**Comment by speters33w** [comment]
Done. Let me know if I need to do anything else with it.

**Comment by speters33w** [comment]
I only updated the install.rst.
You had some edits you did after me to the shell script, the win32 lockout, etc.

**Comment by stuaxo** [comment]
Finally got back to this - thanks, it looks good, we can close this, and make any tweaks we want later on.
