### ISSUE TITLE
MingW64: Gedit extension installer doesn't work.

### ISSUE THREAD

**Issue by stuaxo** [shoebot/shoebot#316]
Trying to install the gedit plugin in MingW64 fails:

```sh
$ python ./extensions/gedit/install.py
Install gedit plugin
Traceback (most recent call last):
  File "C:\Users\Stu\Desktop\projects\mine\shoebot\extensions\gedit\gedit3.12-plugin\install.py", line 161, in <module>
    main()
  File "C:\Users\Stu\Desktop\projects\mine\shoebot\extensions\gedit\gedit3.12-plugin\install.py", line 151, in main
    dirs = get_dirs(is_admin)
  File "C:\Users\Stu\Desktop\projects\mine\shoebot\extensions\gedit\gedit3.12-plugin\install.py", line 88, in get_dirs_nt
    plugin_dir=join(dest_dir, "gedit//plugins"),
  File "C:\Python39\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not tuple

```

**Comment by speters33w** [comment]
I'm not sure this is an issue. 

What is the advantage of using Gedit over any Windows text editor in Windows?

You don't have to use Msys2 consoles for anything but installations and builds on Windows.
Everything can run with a double-click or with command prompt (cmd)

I use Notepad++ to edit bot scripts. I defined .bot as "python language" in Notepad++ and it even gives me syntax highlighting.
A lot of people use Atom, or Jedit. 
I think Atom has that Gedit-like thing with a python console thing going on at the same time as you edit, if that's what you like.

The only thing is you need to ensure Msys2 Python and Bin are in the path environment variable. Most people set this with the environment variables control panel, but. I use a batch file because cmd doesn't keep the paths you create after you exit cmd. Handy if you are using different versions of python.

Here's the batch file I use - pretty simple... 

[python38.bat.txt](https://github.com/shoebot/shoebot/files/5962216/python38.bat.txt)

Here's how I run it. You'll recognize the bot file. I recreated the bug, it's a bug. Those red circles are exported as rasters in an svg, without even a scalable outline, - but that's another issue.

![look_no_msys](https://user-images.githubusercontent.com/25144507/107583846-8a6e1200-6bc9-11eb-8018-ac204d3931a9.png)

**Comment by speters33w** [comment]
Now, I DID try it. It tried to use 
`C:\Python39\lib\ntpath.py`
on your machine, it tried to use
`C:\Python\Python27\lib\ntpath.py` 
on mine.
It's looking in the wrong places.
It needs to find this one:
`\msys64\mingw64\lib\python3.8\ntpath.py`

the `def get_dirs_nt(is_admin):` function in install.py looks almost like a Windows program. 
It's expecting stuff to be where it isn't in mingw64, but would be on a Windows machine.

It's looking here to find python: "%UserProfile%//AppData//Roaming" which is outside of the msys2-O-sphere
That's why it found other python installs for both of us.

**Comment by speters33w** [comment]
I FIXED IT!!!

I added one line to make script use the unix script instead of the windows script.

```
StephanPeters@DESKTOP-QG6GSK0 MINGW64 ~/shoebot/extensions/gedit
$ python install.py
Install gedit plugin
Directory 'C:\msys64\home\StephanPeters/.local/share/mime/packages' does not exist!
install gedit-3.12 plugin to C:\msys64\home\StephanPeters/.local/share
success

StephanPeters@DESKTOP-QG6GSK0 MINGW64 ~/shoebot/extensions/gedit
$
```

**Comment by stuaxo** [comment]
Interesting.. it makes sense gedit MingW on MingW is like Unix.

The original logic was from when we were on python 2.7 and things worked on Windows, but outside MingW.

I guess it makes sense that MingW wants to be Unixy, but I don't want to stop the possibility of installing in a native Windows gedit.

I'll need to come back and play with python in my windows VM - this probably needs something to accommodate both.

**Comment by speters33w** [comment]
If someone uses native Windows gedit and has no other python installed,
they should be able to install for Windows using command line and the old
script.
A nicer solution would be to detect if someone is running under MinG64 even
though the machine is NT and throw them at the unix install.
For the gedit plugin to work on windows gedit user would have to run
shoebot through command line (like I do), not Ming64 terminal.

**Comment by stuaxo** [comment]
The ancient gedit downloadable from the GNOME site probably works (wherever they moved their FTP to).

I should really revive the PR, it gets things working on the gedit forks MINT Linux made: Xed and Plums.

**Comment by stuaxo** [comment]
Gedit support certainly isn't a blocker to release, but it's worth playing with as it's a bit more advanced than the IDE:

You get a menu of all examples and the livecoding feature is enabled.

**Comment by speters33w** [comment]
Well, it does work... I haven't tried using the plugin yet.
I'll see if I can find an old windows exe for gnome I'll have to figure out
how to let Windows know there's a python install it doesn't know about, or
something so it can find the right install files.

**Comment by stuaxo** [comment]
I managed to install gedit using MINGW
https://packages.msys2.org/base/mingw-w64-gedit

Tried changing the PATH detection to this:
```
if os.name == 'nt' and os.path.sep == r'\':
    # Filter path seperator so that MSYS doesn't go down this path for ow
    get_dirs = get_dirs_nt
```

But it does something really weird - when I run `python ./extensions/gedit/install.py`, it displays "Install python plugin.", but then the install.py opens in VSCode !?

**Comment by stuaxo** [comment]
OK, I pushed a couple so that under MSYS it uses get_dirs_unix and it runs the python instead of opening it ..

![image](https://user-images.githubusercontent.com/179677/107621239-d95d8b00-6c4d-11eb-972f-5e61cd905344.png)

I'm pretty sure it installs to the wrong place (gedit doesn't show the plugin) - but at least it does install somewhere, which is a start :)

**Comment by speters33w** [comment]
OK.

I think on this, it's a good time to step back.

I found a Windows native 2016 gedit v 3.20.1 directly from Gnome.

This is what I intend to do: ( you can make this a checklist if you want)

1) Start with my fresh backup of msys2 and follow the directions for
Windows exactly as found on install.rst.

2) Back that up.

3) Edit the plugin installer to see if user is using MinGW or Windows
Command. If command, ignore other python installs and only search for
python files in MinGW install and look for Windows native gedit. If MinGW,
look for msys2 gedit and use Unix plugin install, into correct directories.

4) Attempt to install plugin via MinGW64 with only msys2 gedit installed,
and verify it works.

5) Install gedit for windows, then go back to saved install without msys2
gedit and attempt plugin install via Windows command line.

6) on successful install, see if it even works. If yes, I'll let you know
it's ready, then you can pull files from my Shoebot clone and make sure I
didn't break it for use on Linux. If no, I'll examine using Atom for
Windows to achieve the same thing, and gedit will be the Linux/msys2 thing.

I think it will help you to think of msys2 as an Arch Linux VM under
Windows. It's just a VM that can access Windows resources, environment
variables, user information, installed fonts, etc.
Msys2 Sys is Bash that can't execute Windows binaries.
MinGW64 is a console (minty) that lets you run windows executables, but can
run into trouble compiling.

**Comment by speters33w** [comment]
1) and 2) verified and done.

I have to play with extensions\install.py
Right now it will assume gedit is not installed at all if only the windows
version is installed.

I'll probably write a dummy def for if os is NT but it is called through
windows command line that does nothing (errors out, untill I install
Windows gedit), and if called through MingW64 it will just do exactly what
it does now.
Probably through an "if NT: os.popopen()" unless there is a better way.

**Comment by stuaxo** [comment]
That sounds like a good approach, I reckon it makes sense to concentrate on MINGW gedit,
since the rest of these changes are about getting MINGW to work.


I was poking the installer and changed the install directory to the global MINGW64 gedit plugins directory:
`/mingw64/lib/gedit/plugins/`
But.. the installer isn't writing any files, even though I can, as a user.

For some reason `os.path.isdir()` returns `False` when it's looking for the directories to write to.
There seemed to be a similar thing with `os.listdir()` - the installer uses both.

I wonder if it's the same as this one triggered by the windows file redirector?
https://stackoverflow.com/questions/19187812/os-listdir-cant-see-my-directory

Some of that legacy code, is a version of copytree, in the installer, for python 2.5 compatibility, we could
probably just use shutil.copytree here.


To try it anyway: I zipped up a copy from ubuntu and extracted it in the plugin directory.
[shoebotit.zip](https://github.com/shoebot/shoebot/files/5968705/shoebotit.zip)

Once enabled in the plugins list, it does come up, and you can run code in shoebot with Ctrl-R.

Some things aren't quite right though..
 - [ ] Console windows come up, this might be fixable, by changing how it launches sbot in a subprocess
       It looks like there might be a solution:
       https://code.activestate.com/recipes/409002-launching-a-subprocess-without-a-console-window/

 - [ ] Loading examples from the menu doesn't work, it doesn't like urls starting with `file:///` so, for Windows it will probably have to drop the `file:///` bit of the URL.
![image](https://user-images.githubusercontent.com/179677/107705819-40635a00-6cb7-11eb-86b7-6913ccbae14e.png)

Where to install as a user in MINGW ?

This is a bit of a mystery...
Under Linux, the plugins are relative to $XDG_DATA_HOME, so it ends up in `~/.local/share/gedit/plugins`.

If you're trying to debug stuff in the gedit plugin itself:

You can just edit the code in the directory its installed to, restart gedit and it'll pick it up.
If there's an exception, the plugin will get disabled and you'll need to re-enable it in the plugin list next time.


So there are two things - errors in the plugin, and errors in the installer.  
The installer has some *very* legacy code, so it might be easier to fix bugs in the plugin than the installer.
Having said that, do whatever is easiest / most fun to hack on.

I'm probably not going to get much time to look at Shoebot stuff until Monday, though I'll should see the updates on issues etc, have a good one :)

**Comment by speters33w** [comment]
It's going to be Monday for me to seriously look at it, too. I'm thinking
os.popout(uname -s) will be a quick and easy way to see if they're using
MinGW64. Console returns "'uname is not recognized as an internal or
external command." Ming returns "MINGW64_NT-(Windows Version), so that
should work.
I think WSL is isolated, but even if it returns something if someone is
using WSL, it won't start with MINGW64.
The python we installed can't be run in the other terminal modes.

**Comment by speters33w** [comment]
This works:

```
import subprocess

MinGW64 = False
uname_s = subprocess.Popen("uname -s", shell=True, stdout=subprocess.PIPE)
if str(uname_s.stdout.read())[2:9] == 'MINGW64':
    MinGW64 = True
```

**Comment by speters33w** [comment]
So does this. Returns True in Command Prompt, False in MinGW64.

```
import subprocess

Windows = False
cmdver = subprocess.Popen("ver", shell=True, stdout=subprocess.PIPE)
if str(cmdver.stdout.read())[16:23] == 'Windows':
    Windows = True
```

**Comment by speters33w** [comment]
As far as where to put the plugin, nosing around in this tarball might be helpful.

https://packages.msys2.org/package/mingw-w64-x86_64-gedit-plugins?repo=mingw64

**Comment by stuaxo** [comment]
OK, I have a version locally that works but needs redoing nicely to push up here.

Notes so I can put up a version of this as a PR:

This solutions stop it spawning console windows on launch.
https://stackoverflow.com/questions/10637450/how-to-hide-console-with-popen-on-windows
https://stackoverflow.com/questions/3390762/how-do-i-eliminate-windows-consoles-from-spawned-processes-in-python-2-7

Changing the way that new tabs are open to use file paths gets the examples menu work.
`using gio_file = Gio.file_new_for_path(uri)`  (and removing the `file:///` portion of the path).

The plugin directory for users, was found running gedit in process explorer
`C:\Users\Stu\AppData\Local\gedit\plugins` - so %LOCALAPPDATA%\gedit\plugins

Slowness:  The plugin searches all python envs and runs sbot to query it's version, this is fast enough on Linux, but slow in a Windows VM.

**Comment by speters33w** [comment]
I think it's getting python install info from %user%/local/appdata, and
that contributes to the slowness.
Plus the MinGW python won't be there.

Maybe a MingW only function for that part of the install?

After the install it works OK?

**Comment by stuaxo** [comment]
It seemed to be a bit of slowdown on enabling the plugin, and every time gedit was started, but can't reproduce any more :shrug: 

There's a draft PR here you can try
https://github.com/shoebot/shoebot/pull/329

Syntax highlighting doesn't work yet. - this is because we need to work out where to install it, so that gedit picks it up.
Livecoding doesn't work, but this is an upstream bug in python-meta on python 3.8 and up.

**Comment by stuaxo** [comment]
Merged... syntax highlighting doesn't seem to work on other platforms so wasn't a MingW64 issue.
Livecoding is also a cross-platform issue.

Give things a test + I think this bug can be closed :)

**Comment by speters33w** [comment]
OK. It will probably be Monday.

**Comment by stuaxo** [comment]
Absolutely no rush :)

It's going to take a while longer to resolve some of the other important bugs.

**Comment by stuaxo** [comment]
Closing, since the other issues are not MINGW64 specific.
