### ISSUE TITLE
Add support for another operating system: Manjaro

### ISSUE THREAD

**Issue by villares** [shoebot/shoebot#326]
Following instructions from https://github.com/shoebot/shoebot/blob/master/doc/source/install.rst

I'm trying to install shoebot on Manjaro... I'm very unskilled on Linux, let's see if I can make it work, sorry if this issue is not very usefull right now :)

- Trying to install: Pycairo  PyGObject3 Pango
      - PyGObject3 failed 
- I think I have Pillow GTK3 and GTKSourceView3 already 

- If I manage to install PyGObject3, what would be the next step, for dummies? 

Question, could we have perhaps an AppImage? Is it hard to create/maintain?

If all else fails I'll try my ShoebotBox on VirtualBox :D

**Comment by villares** [comment]
UPDATE: I tried `python setup.py install` and it looks like it worked...

I have no idea of what I have done... 

![image](https://user-images.githubusercontent.com/3694604/107866335-6a9b5000-6e4e-11eb-91b4-57f51f1fb5bc.png)

**Comment by villares** [comment]
Should we close this issue?

Would you like to coach me on trying to add Manjaro to the installation shell script?

**Comment by stuaxo** [comment]
The first thing is to run the install script and paste the output here.

`./install/install_dependencies.sh`

We also need to know what package manager Manjaro uses, then we can go from there.

Then we need to work out the names of the required packages, if we are lucky they will be the same as ones in another distro.

**Comment by villares** [comment]
```
Shoebot does not directly support ManjaroLinux 20.2.1 at the moment.

Get started by looking at "Add support for another operating system".
in the installation documentation.
```

So the package manager is `pacman` but I don't know much more than this :D

**Comment by stuaxo** [comment]
If you list your installed packages, that could be a start since you already have it working: `pacman -Q`  [1]

Then we need to see which ones look like they are equivalents to either the DEB_PACKAGES or FEDORA_PACKAGES below:

```
# Fedora, Redhat, (Centos?)
FEDORA_PACKAGES="redhat-rpm-config gcc cairo-devel libjpeg-devel python3-devel python3-gobject cairo-gobject"

# Debian, Ubuntu, Mint (keep in alphabetical order: tested to match those in .travis)
DEB_PACKAGES="build-essential gir1.2-gtk-3.0 gir1.2-rsvg-2.0 gobject-introspection libgirepository1.0-dev libglib2.0-dev libgtksourceview-3.0-dev libjpeg-dev libpango1.0-dev python-gi-cairo python-gobject python3-dev"
```

[1] https://linuxhint.com/list_installed_packages_pacman_arch_linux/

**Comment by villares** [comment]
This is the closest I could find, does it even make sense?
```
cairo 1.17.4-3
cairomm 1.12.2-4
libjpeg-turbo 2.0.6-1
python 3.9.1-1
python-gobject 3.38.0-3
gtk3 1:3.24.24-2
librsvg 2:2.50.3-1
gobject-introspection 1.66.1-3
gobject-introspection-runtime 1.66.1-3
pango 1:1.48.1-1
pangomm 2.46.0-1
python-cairo 1.20.0-3
gtksourceview3 3.24.11+28+g73e57b57-1
```

**Comment by stuaxo** [comment]
Cheers, it does.

It looks like Arch and Manjaro share the same packages, so I've added them here:  https://github.com/shoebot/shoebot/pull/328

This needs testing before we can merge it.   
Even though you already have the packages installed it would be useful if you checkout the branch on the PR and see if it throws up any errors.

We really need to test on an empty VM and verify it installs everything that's needed.

**Comment by villares** [comment]
I have downloaded the branch and tried the install script, but I get something like "Syntax error on line 207, unexpected End Of File":
```
./install_dependencies.sh: linha 207: erro de sintaxe: fim prematuro do arquivo
```

**Comment by rlafuente** [comment]
I've fixed the typo that led to that error, can you pull and try again? (thanks for sticking through all this!)

**Comment by villares** [comment]
It is a great pleasure to be able to contribute to this wonderful project.
Such a tiny contribution to be sure. I'll run it again as soon as I can.
I'm away from the desktop today.

**Comment by villares** [comment]
I forgot to activate a virtual environment, so it kind of installed lots of stuff:
```
Arch is in testing, please report any problems to https://github.com/shoebot/shoebot
atenção: cairo-1.17.4-3 está atualizado -- reinstalando
atenção: gobject-introspection-1.66.1-3 está atualizado -- reinstalando
atenção: gobject-introspection-runtime-1.66.1-3 está atualizado -- reinstalando
atenção: gtk3-1:3.24.24-2 está atualizado -- reinstalando
atenção: gtksourceview3-3.24.11+28+g73e57b57-1 está atualizado -- reinstalando
atenção: libjpeg-turbo-2.0.6-1 está atualizado -- reinstalando
atenção: librsvg-2:2.50.3-1 está atualizado -- reinstalando
atenção: pango-1:1.48.1-1 está atualizado -- reinstalando
atenção: python-3.9.1-1 está atualizado -- reinstalando
atenção: python-cairo-1.20.0-3 está atualizado -- reinstalando
atenção: python-gobject-3.38.0-3 está atualizado -- reinstalando
resolvendo dependências...
procurando pacotes conflitantes...

Pacotes (11) cairo-1.17.4-3  gobject-introspection-1.66.1-3  gobject-introspection-runtime-1.66.1-3
             gtk3-1:3.24.24-2  gtksourceview3-3.24.11+28+g73e57b57-1  libjpeg-turbo-2.0.6-1  librsvg-2:2.50.3-1
             pango-1:1.48.1-1  python-3.9.1-1  python-cairo-1.20.0-3  python-gobject-3.38.0-3

Tamanho total download:    33,94 MiB
Tamanho total instalado:  192,29 MiB
Alteração no tamanho:     0,00 MiB

:: Continuar a instalação? [S/n] s
:: Obtendo pacotes...
 cairo-1.17.4-3-x86_64                   635,8 KiB   304 KiB/s 00:02 [######################################] 100%
 gobject-introspection-runtime-1.66...   219,5 KiB  2,38 MiB/s 00:00 [######################################] 100%
 python-3.9.1-1-x86_64                    31,7 MiB  2,09 MiB/s 00:15 [######################################] 100%
 libjpeg-turbo-2.0.6-1-x86_64            407,1 KiB  1967 KiB/s 00:00 [######################################] 100%
 gtksourceview3-3.24.11+28+g73e57b5...   721,1 KiB  2003 KiB/s 00:00 [######################################] 100%
 python-cairo-1.20.0-3-x86_64             61,5 KiB  2,61 MiB/s 00:00 [######################################] 100%
 python-gobject-3.38.0-3-x86_64          254,4 KiB  1957 KiB/s 00:00 [######################################] 100%
(11/11) verificando chaves no chaveiro                               [######################################] 100%
(11/11) verificando integridade do pacote                            [######################################] 100%
(11/11) carregando arquivos do pacote                                [######################################] 100%
(11/11) verificando conflitos de arquivos                            [######################################] 100%
(11/11) verificando espaço em disco disponível                       [######################################] 100%
:: Processando alterações do pacote...
( 1/11) reinstalando cairo                                           [######################################] 100%
( 2/11) reinstalando gobject-introspection-runtime                   [######################################] 100%
( 3/11) reinstalando python                                          [######################################] 100%
( 4/11) reinstalando gobject-introspection                           [######################################] 100%
( 5/11) reinstalando pango                                           [######################################] 100%
( 6/11) reinstalando libjpeg-turbo                                   [######################################] 100%
( 7/11) reinstalando librsvg                                         [######################################] 100%
( 8/11) reinstalando gtk3                                            [######################################] 100%
( 9/11) reinstalando gtksourceview3                                  [######################################] 100%
(10/11) reinstalando python-cairo                                    [######################################] 100%
(11/11) reinstalando python-gobject                                  [######################################] 100%
:: Executando hooks pós-transação...
(1/6) Arming ConditionNeedsUpdate...
(2/6) Probing GDK-Pixbuf loader modules...
(3/6) Compiling GSettings XML schema files...
(4/6) Probing GTK3 input method modules...
(5/6) Updating icon theme caches...
(6/6) Updating the desktop file MIME type cache...
``` 
I see no error messages, but `shoebot` is not found if called from the terminal.
(I don't know how to add it to PATH. If I activate my previous environment it works fine.)

**Comment by stuaxo** [comment]
Thanks :)

The script only installs the libraries shoebot needs, not shoebot itself.
There shouldn't be any *new* packages, as the list is based off the one you provided, so hopefully just upgraded what you already have.

Maybe the script needs a message at the end along the lines of "You can now install shoebot".

**Comment by rlafuente** [comment]
Added a simple message in 075fac0, not sure whether to also include the setup.py install command?

**Comment by stuaxo** [comment]
It could be worthwhile, though anyone installing with pip probably won't see it as it hides stdout by default.

**Comment by villares** [comment]
Woderful!

Some naïve questioning and a caveat:
- What prevents us of having an`install_shoebot.sh` that installs dependencies and *shoebot* itself? Is it too hard to mantain?
- I tried to look for packages with similar names to the ones shown, but, *I have no idea if I have picked all that is needed **or even if I picked some that are not needed but looked like the ones needed***.

**Comment by stuaxo** [comment]
> Wonderful!
> 
> Some naïve questioning and a caveat:
> 
>     * What prevents us of having an`install_shoebot.sh` that installs dependencies and _shoebot_ itself? Is it too hard to mantain?

The dependencies that install_shoebot.sh installs are mostly things installed as root.
When it comes to python apps, such as shoebot, it's good practice not to install them in the system python (which installing shoebot would do).

> 
>     * I tried to look for packages with similar names to the ones shown, but, _I have no idea if I have picked all that is needed **or even if I picked some that are not needed but looked like the ones needed**_.

That's fine, I checked them against the ones we had, and removed ones I knew we didn't.
If some are missing and someone will arrive on the bug tracker and tell us.

Installation is probably our biggest challenge, and the script is a sort of hack-around it.   
Getting the libraries we use: Cairo, Pango and Gtk setup for users has eaten huge amounts of time, and made it impossible to for something simple like `pip install shoebot` to "just work".

Work upstream has probably helped a bit, e.g. work to help pycairo easier to install, but there is still work to go.

Ultimately, without a massive rewrite we are kind of stuck.

(If the rewrite emerges, it will change in other too, such as no longer following the Nodebox1 API).

**Comment by rlafuente** [comment]
Including an automatic dependency is not an usual method -- maybe we could add the installation steps to the documentation? And mention that you can either run that script, or follow the steps. Just throwing around the idea, I can take care of it if OK.

**Comment by stuaxo** [comment]
> Including an automatic dependency is not an usual method -- maybe we could add the installation steps to the documentation? And mention that you can either run that script, or follow the steps. Just throwing around the idea, I can take care of it if OK.

Yes, that sounds good.   

**Single source of truth for package dependencies:**
It would be good to have one source of truth for the lists of packages, I'm interested to hear ideas on what this should be.

Right now, it's the script - we have a unittest [1] that checks the package list for debian is the same as in our travis script.
If you add the docs, we should probably add a test to make sure the docs are in sync with it.

Ultimately something else should be the source of truth though - The script isn't optimal if we want to do things in the future like show the user a hint `pip install shoebot` fails, and probably other use cases.

Maybe the docs themselves could be the source of truth (though that might be a tricky to grab the package lists?) ?

The thing stopping us from using distro package definitions as our source of truth is that there is at least one dependency (python meta) that isn't packaged, but maybe we could use something else or make this optional.


[1] Test that verifies the travis package list is in sync with the script:
https://github.com/shoebot/shoebot/blob/master/tests/unittests/test_travis_configuration.py#L48-L59

**Comment by rlafuente** [comment]
good one -- anyway the Manjaro dependencies are taken care of, right? we can perhaps close this?

**Comment by stuaxo** [comment]
Almost.. the script misinterprets Manjaro as Arch, so once that's fixed then yes.

(A small thing, but could hinder debug later)

**Comment by stuaxo** [comment]
OK, one last tweak..  I've tried to fix the Arch vs Manjaro detection + added an option to show the OS that is detected without installing anything.

@villares are you up for testing the latest version on the PR here ?
https://github.com/shoebot/shoebot/pull/328

If you run `./install/install_dependencies.sh -o  -p` it should show it's running under Manjaro, and I then I can merge it and close this ticket.

**Comment by villares** [comment]
Hmmm, I have downloaded this branch: https://github.com/shoebot/shoebot/tree/arch-manjaro
But I get this message (tried twice to be sure I got the right branch...):
```
[villares@L340 shoebot-arch-manjaro]$ ./install/install_dependencies.sh -o -p
Shoebot does not directly support ManjaroLinux 20.2.1 at the moment.

Get started by looking at "Add support for another operating system".
in the installation documentation.
```

**Comment by stuaxo** [comment]
Most likely I have introduced a bug, will have another look.

Thanks for testing.

**Comment by villares** [comment]
Hi @stuaxo, please be advised I downloaded the branch (I wouldn't know how to get the script from the PR, unless instructed step by step).

**Comment by stuaxo** [comment]
If you don't have git installed the easiest way might be to grab a copy of from here
`https://github.com/shoebot/shoebot/blob/arch-manjaro/install/install_dependencies.sh`

And replace the contents of yours with it.


I had a look at the log you sent earlier + added a fix based on it just now, so hopefully it's good now.

**Comment by villares** [comment]
:smile: 
```
[villares@L340 install]$ ./install_dependencies.sh -o -p
ManjaroLinux, 20.2.1
pacman
```

**Comment by stuaxo** [comment]
Fantastic, I will merge this.

Thanks for the help with testing.
