### ISSUE TITLE
Variable fonts: implement in font()

### ISSUE THREAD

**Issue by rlafuente** [shoebot/shoebot#335]
Variable fonts are an option for us, and with Pango supporting them, I can give a shot at implementing them in Shoebot.

Since it's not a Node box feature, we should look elsewhere for ideas on how to provide this feature -- which new functions should we bring?

I was looking at Drawbot which uses [listFontVariations](https://www.drawbot.com/content/text/textProperties.html#drawBot.listFontVariations) and other commands for this. 

I think we don't use camelCase in Shoebot, so not sure about importing the Drawbot commands as they are. (we can have aliases to the camelCase commands though, so we can be somewhat compatible)

Any thoughts about this?

**Comment by stuaxo** [comment]
We should stick with underscore_case for consistency.

If the version of pycairo / pango needed is very new then we will might need to check the version and only enable if it's available.

If there are other APIs that support variable fonts it's worth looking at all of them + seeing which ones have the best ideas.

**Comment by rlafuente** [comment]
OK this was implemented in text(), but we also want this to work in font(). Changing the issue title to reflect this

**Comment by stuaxo** [comment]
If it's the same code as in text() might not need it's own PR, could just go on the text() one ?

**Comment by rlafuente** [comment]
this is already implemented, yay
