### ISSUE TITLE
Host our own documentation?

### ISSUE THREAD

**Issue by rlafuente** [shoebot/shoebot#336]
Readthedocs is not working well because of our eccentric dependencies, and as a result our public docs are very outdated.

I can set up docs.shoebot.org and put our generated documentation there. But I'm wondering about the downsides?

**Comment by villares** [comment]
Hmmm, more maintenance work? but then, it is broken as is so...

**Comment by stuaxo** [comment]
Storing the generated images might be an option - we could keep a hash so that we know if they need regenerating or not.

That way we could avoid that step on RTD, then manually regenerate as needed.

**Comment by rlafuente** [comment]
docs.shoebot.net is up, maybe we take down the RTD site?

**Comment by rlafuente** [comment]
Docs migrated and homepage+README references updated!
