### ISSUE TITLE
Remove the "Save as __" options in the right click menu until we fix snapshots

### ISSUE THREAD

**Issue by rlafuente** [shoebot/shoebot#365]
They give out the wrong idea that saving current state is possible, but it's buggy at the moment and silently fails

**Comment by stuaxo** [comment]
It seems like "Save as" saves animations OK - but not the non-animated bots.
(and I've been using hypnoval.bot as my goto test since forever).

I don't think we need to remove it, but we probably need to make it a blocker to fix before a release ?

**Comment by stuaxo** [comment]
Closing as this seems fixed for now, and we have tests.

(Though in CI, something is wrong with some output which is a different issue).
