### ISSUE TITLE
Socket server fails on client connection

### ISSUE THREAD

**Issue by rlafuente** [shoebot/shoebot#367]
Trying to connect with `telnet localhost 7777`, it does connect but the shoebot process errors out with

```
Traceback (most recent call last):
  File "/home/rlafuente/.virtualenvs/shoebot/lib/python3.9/site-packages/PyGObject-3.38.0-py3.9-linux-x86_64.egg/gi/overrides/GLib.py", line 671, in <lambda>
    func_fdtransform = lambda _, cond, *data: callback(channel, cond, *data)
  File "/home/rlafuente/repos/shoebot/shoebot/sbio/socket_server.py", line 85, in listener
    f = conn.makefile(conn)
  File "/usr/lib/python3.9/socket.py", line 310, in makefile
    if not set(mode) <= {"r", "w", "b"}:
TypeError: 'socket' object is not iterable
```

**Comment by stuaxo** [comment]
Maybe makefile changed in python 3?

Looks like we need a test if we fix this.

**Comment by stuaxo** [comment]
Unless it's a 3.9 change, can you try 3.8?

**Comment by rlafuente** [comment]
this is because the makefile call is using `conn` as a first argument, when it should be the socket mode ([docs](https://docs.python.org/3/library/socket.html#socket.socket.makefile))

With the `r` argument, telnet connection is successful, but the socketserver fails while trying to write the intro message to the socket -- error is `io.UnsupportedOperation: not writable`

OTOH with the `w` argument, the shell welcome message appears, but any command like "help" gives the error `io.UnsupportedOperation: not readable`

**Comment by rlafuente** [comment]
Aha `rw` works (the docs really don't make clear that this is an option) -- https://github.com/shoebot/shoebot/pull/368

**Comment by stuaxo** [comment]
I wonder if `rwb` might be the thing to use, often in Windows `b` is needed too.
