### ISSUE TITLE
Add option to arc() for an alternate shape

### ISSUE THREAD

**Issue by rlafuente** [shoebot/shoebot#371]
Right now we have the cairo behavior with closing arcs, which connects the start and end points:

![Screenshot_2021-04-04_23-21-15](https://user-images.githubusercontent.com/159868/113522938-7d074f80-959c-11eb-8785-f38e213b8326.png)

But PlotDevice has a [more interesting approach](https://plotdevice.io/ref/Primitives#arc()) to closed arcs:

![Screenshot_2021-04-04_23-20-53](https://user-images.githubusercontent.com/159868/113522937-7b3d8c00-959c-11eb-998f-a8372b361d39.png)

We could provide an option to select the plotdevice way to draw. Can't think of a simple name for this...

**Comment by stuaxo** [comment]
This is interesting, pie charts are definitely useful.

It did start me thinking about some API for shapes that had an idea of different styles but maybe there's complexity in there !

**Comment by villares** [comment]
This is the Processing `arc()`:
![image](https://user-images.githubusercontent.com/3694604/113611829-6e18af80-9625-11eb-9532-5358c550efa0.png)

Maybe a keyword argument for the mode?

**Comment by rlafuente** [comment]
I just pushed a first decent stab at this on the arc-last-bits branch (see #343), here's how it works:

- arc() has a new keyword argument `type` (following the arrow() syntax) with a default value of `CHORD`
- with `PIE` it adds 2 lines to the arc path, resulting in the pie chart shape

So you could call `arc(20, 20, 100, 40, 20, type=PIE)`

Does this syntax work for you?

**Comment by rlafuente** [comment]
(also, that's a nice thing to screenshot the relevant part of the Processing docs instead of linking it, clever! Much easier to process, thanks :)
