### ISSUE TITLE
Docs: Decide on structure for command reference

### ISSUE THREAD

**Issue by rlafuente** [shoebot/shoebot#381]
Right now we're at a nice spot -- we cleaned the documentation build system, made it prettier and a lot faster. So most of the pain points of working on docs are gone.

Now looking into the content and thinking about how to better structure things, there's one that I'd love to get feedback about -- how to most effectively list the command reference.

Right now, we have a long, long page. It has the great feature to allow you to get a wider view of what can be done by quickly scrolling and skimming the visual examples. However, it can be a bit overwhelming, and the lack of a sidebar or table of contents makes it hard to reach a specific command. It also makes it unwieldy to have long command descriptions or multiple examples for one command, which is needed in some cases.

Nodebox has an [index page](https://www.nodebox.net/code/index.php/Reference.html) of all the commands and a dedicated page for each command, with a description and one or more examples.

Drawbot's [command documentation](https://www.drawbot.com/) groups commands into sections. The choice of sections and the internal layout of each page are a bit confusing to me at times, but I find that going through the docs is a lot more digestible and parseable with this approach.

PlotDevice's [manual](https://plotdevice.io/manual) uses sections but combines them with a comprehensive index like Nodebox. Their docs are also superclean, it would be fun to try and twist Sphinx to support this kind of column layout for the indexes.

I'm inclined towards the PlotDevice way of doing things, but wondering if there's any strong opinions as well.

**Comment by stuaxo** [comment]
Whatever we do I'd like links to work, at least one of these (maybe plot device ?) had a weird mechanism if I recall.

**Comment by rlafuente** [comment]
This is now done with proper sections in the [docs](https://docs.shoebot.net/commands.html). Still missing a TOC, but i moved that to #382
