### ISSUE TITLE
Video export

### ISSUE THREAD

**Issue by rlafuente** [shoebot/shoebot#392]
We're at a point where creating videos is possible, using the `--repeat` command line option to generate multiple images and putting them together with ffmpeg. This works:

```bash
sbot script.bot -r 90 -o tmp/test.png
ffmpeg -r 30 -f image2 -pattern_type glob -i "tmp/test*.png" -c:v libx264 -crf 20 -movflags faststart -c:a aac -pix_fmt yuv420p out.mp4
```

I'm now trying to find the simplest way to integrate these commands into Shoebot proper, and don't yet know the best strategy. 

Maybe detect early (before creating bots) if the filetype is a video format, and if so generate the images into a temp dir and run ffmpeg?

**Comment by stuaxo** [comment]
Have a lot at the Runner class in Nodebox.
Organising things that way would make this easier.

**Comment by stuaxo** [comment]
It'll be a lot easier post 1.4 as I started prototyping using that patter but adapted for modern python.

**Comment by rlafuente** [comment]
yep we now have video \o/ we'll make that neater post-release
