### ISSUE TITLE
Use cairo backend to generate PDF

### ISSUE THREAD

**Issue by jabiertxof** [shoebot/shoebot#404]
Folowing previous issues I open it to have shoebot exports as vectorial when possible PDF using Cairo backend (no Pillow)

**Comment by rlafuente** [comment]
Have you tried using a filename with the `.pdf` extension in `create_bot`? Because pdf export should just work

**Comment by jabiertxof** [comment]
Sorry I dont know (and dont test :)) great close the issue.

**Comment by jabiertxof** [comment]
I try to export a vectorial pdf now and report stuaxo

**Comment by jabiertxof** [comment]
Is exported as vectorial file!

**Comment by jabiertxof** [comment]
sorry for the noise, but not fast find what extensions manage the output of the program in a fast search in doc. Is a big point in favor so seems good make more visible
