### ISSUE TITLE
Saving a snapshot of a script with draw() repeats more than 300 times

### ISSUE THREAD

**Issue by rlafuente** [shoebot/shoebot#411]
Saving in the right-click menu works as expected in scripts without a draw() function.

But if draw() is present, the snapshot call is done repeatedly:

```
Save snapshot: 29-dashes.svg
Save snapshot: 29-dashes.svg
Save snapshot: 29-dashes.svg
Save snapshot: 29-dashes.svg
Save snapshot: 29-dashes.svg
Save snapshot: 29-dashes.svg
```

and the amount varies, i tried twice -- got 354 and 376

**Comment by rlafuente** [comment]
this also happens when speed() is not set (and currently results in a static image)

**Comment by stuaxo** [comment]
Can you add some good old print based debug:

```
import sys
print(f"global scope {FRAME}")

def setup():
    print(f"setup() {FRAME}")

def draw():
    print("draw() {FRAME}")

    sys.exit()
```

Initially try setting to something low, like `1`, to keep the output sane, then try varying it.

**Comment by stuaxo** [comment]
Pinned:  This will be the first bug after LGM from my side.

This is a good reason to finally add some proper logging - starting in the main loop (and maybe in the livecoding) to see what's going on.

**Comment by stuaxo** [comment]
Fixed in master... I can leave out adding logging to another bug :)

Didn't fix the other issue where some of the outputs freeze in the CI.
