### ISSUE TITLE
Could not build wheels for pygobject which use PEP 517 and cannot be installed directly

### ISSUE THREAD

**Issue by chuongmep** [shoebot/shoebot#421]
Hello everyone,
Whether we have any update  in feaure ? 
Im using python 3 and it show with some shell: 
```
pip install p5py
pip install PEP517
```
and some command to update 
```
pip install --upgrade pip setuptools wheel
```
but it not working for me at the moment.any solution is appreciated!
![image](https://user-images.githubusercontent.com/31106432/131776493-3c9da72b-ca97-4d07-b3aa-3920f4466086.png)

**Comment by rlafuente** [comment]
This seems like a pygobject/pep517 problem, unrelated to Shoebot. Feel free to reopen the bug if you think it has to do with Shoebot!
