### ISSUE TITLE
collections.Mapping not supported anymore in Python 3.10

### ISSUE THREAD

**Issue by vanderaalle** [shoebot/shoebot#443]
Sorry for bad formatting, not used to work on github.
After installing shoebot again in ubuntu 22.04 (I was on 20.04) I was not able to import shoebot module. Turned out that in events.py there is a call to collections.Mapping. Now, this is not supported anymore in Python >= 3.10 (default on 22.04).
It seems that I solved by changing collections.Mapping into collections.abc.Mapping as suggested here:

https://stackoverflow.com/questions/72419139/ipyvolume-in-windows-issue-attributeerror-module-collections-has-no-attribute
 
Best
-a-

**Comment by stuaxo** [comment]
Fixed in master.
