### ISSUE TITLE
Port data structures to lib2geom

### ISSUE THREAD

**Issue by stuaxo** [shoebot/shoebot#58]
[Ported from trac issue 81 @rlafuente ]

Porting the primitives data structures (Rect, Ellipse, BezierPath?) and transforms (Matrix) to lib2geom would help solve some of our current bottlenecks.

The effort for this would be checking if the 2geom Python bindings suit all our needs, as well as compiling 2geom for inclusion in the Shoebot package.

**Comment by rlafuente** [comment]
It looks like 2geom isn't being actively maintained (last commit in 2016), so this is probably not a good move anymore.

Now there's the Python [bezier](https://github.com/dhermes/bezier) library which deals with path representations and intersections (which would be useful), but its dependency on libfortran and NumPy might be a bit troublesome...

**Comment by stuaxo** [comment]
2geom on github is more recent  https://github.com/inkscape/lib2geom

You're right though, bezier looks like a much better bet - being pypi installable and documented.
It looks like they [include these libraries inside the WHL file](https://bezier.readthedocs.io/en/latest/native-libraries.html ), so most users might be fine ?

The only thing missing is conversion between  bezier->cairo_path.
Hopefully they would accept that upstream, so less code to maintain here.

**Comment by rlafuente** [comment]
Moving the discussion to #166
