### ISSUE TITLE
Support geometry operations via lib2geom

### ISSUE THREAD

**Issue by stuaxo** [shoebot/shoebot#59]
[Ported from trac 32 @davelab6 @rlafuente ]

Integrate lib2geom support so that scripts can do simple path operations (union, intersect, etc)

**Comment by rlafuente** [comment]
2geom isn't actively maintained and it doesn't seem a good option to provide this functionality. 

Maybe [Shapely](https://shapely.readthedocs.io/en/latest/) can work for this?

**Comment by rlafuente** [comment]
Moving discussion to #166
