### ISSUE TITLE
Update and publish Geany config

### ISSUE THREAD

**Issue by stuaxo** [shoebot/shoebot#63]
Spryte (a distribution of shoebot for windows) came with a shoebot conf.

This should be updated and added under the extensions directory.

http://spryte.hxgraphics.com/

**Comment by rlafuente** [comment]
The site's gone, I found a [snapshot](https://web.archive.org/web/20111002022012/http://spryte.hxgraphics.com/) at the Internet Archive but there seems to be no trace of the source code... maybe we close this?

**Comment by stuaxo** [comment]
Sounds good to me.
