### ISSUE TITLE
Clarify how transforms work more clearly

### ISSUE THREAD

**Issue by rlafuente** [shoebot/shoebot#79]
From Simon Budig:

```
I am more used to a cairo-like transformation model. To me it is
really weird how a "scale" operation by default does not affect
the x and y coordinates of an object.
```

Our particular way of doing things must be clearly explained. Maybe a specific docs section for Cairo people would be useful.

**Comment by stuaxo** [comment]
Def need a doc ... about cairo differences, and a doc about nodebox differences.
