### ISSUE TITLE
ipython integration

### ISSUE THREAD

**Issue by stuaxo** [shoebot/shoebot#89]
Shoebot django  https://github.com/shoebot/shoebot-django  shows rendering svg to the browser, ipython support could work in a similar way

**Comment by stuaxo** [comment]
Basic cairo render hook -
https://github.com/stuaxo/ipython_cairo

Though would be really good to get this animated like ivisual

**Comment by davelab6** [comment]
wow, awesome :))

**Comment by stuaxo** [comment]
Ah, now I have to go implement this, doh ;)

**Comment by davelab6** [comment]
ipython on sandstorm.io is cool

**Comment by stuaxo** [comment]
Implemented in other ticket, we can open new tickets for bugs / improvements
