### ISSUE TITLE
install scripts do not complete on OpenSuSE

### ISSUE THREAD

**Issue by stuaxo** [shoebot/shoebot#92]
./install_dependencies.sh

mkvirtualenv shoebot
./setup_virtualenv -c
- Has some trouble compiling numpy.

**Comment by stuaxo** [comment]
Script is currently out of date #108

**Comment by rlafuente** [comment]
Numpy is not a required dependency for Shoebot core, only for the `audio` and `sbvideo` libraries. If this is still an issue, we could consider removing it as a base dependency...

**Comment by stuaxo** [comment]
Every time this bites us I think of splitting things up, just haven't been able to face it / find the time so far.

Having said that, I don't know why numpy shouldn't be installable on OpenSuse - I haven't tried for a long time, maybe it works now ?


This is my current thinking on splitting (these are the packages, repos might not be the same, but may as well be) - 

shoebot-core     
- all the code for running shoebot
- this is basically the shoebot repo renamed, with examples removed (+ extensions, but that is in progress)
dependencies:  everything needed to run shoebot headless (gui is optional)

shoebot-examples
 - examples
dependencies: all example dependencies

shoebot
- empty package, it's purpose is to install everything shoebot
dependencies: shoebot-core, shoebot-examples,  gui libraries

Maybe, then - the ide would become it's own thing that 'shoebot' depends on as well:

shoebot-ide
dependencies: shoebot-core, shoebot-examples, plugin-shoebot

**Comment by stuaxo** [comment]
This ticket tracks splitting plugin-shoebot  [ Reorganise extensions/lib/shoebotit #147 ](https://github.com/shoebot/shoebot/issues/147)

**Comment by stuaxo** [comment]
Updated SuSE dependencies - could always do with more testing.
